// Generated from the local Kyu/Dan syllabus extracts. Run scripts/generate-kamoku-summary-fallbacks.py to refresh.
export const kamokuSummaryFallbacks: Record<string, string> = {
  "tanto tsuki komi shita uke uchi otoshi geri": "Posicion: tai gamae. Atacante: cuchillada chudan. Defensor: hasso; golpea la muñeca (yokei) uchi otoshi",
  "kinteki (gyaku) geri hiza uke nami gaeshi": "Posicion: tai gamae. Atacante: jun kinteki geri. Tambien desde hiraki (gyaku geri)",
  "tanto tsuki komi shita uke geri kote nage": "Posicion: tai gamae. Atacante: cuchillada chudan. Defensor: hasso gamae",
  "kiri kaeshi tembin (katate & morote)": "Posicion: hiraki gamae. Atacante: empuja alejando directo a resistir kiri gote Defensor: gyaku gedan gamae",
  "ude gyaku dori to morote maki gote": "Posicion: tai gamae. Atacante: intento de ude gyaku dori (maki tembin) Defensor: ura gatame",
  "dan geri sambo uke dan geri gaeshi": "Posicion: tai gamae. Atacante: jun dan geri (kinteki, mawashi)",
  "mawashi geri sambo uke nami gaeshi": "Posicion: tai gamae. Atacante: jun mawashi geri a gedan, chudan o jodan",
  "kote nage from jo chu ni ren zuki": "Posicion: cualquier kamae indicado. Como en tai ten ichi o tsuki ten ichi",
  "sokuto geri hiki ashi nami gaeshi": "Posicion: cualquier kamae indicado. Atacante: gedan jun sokuto geri (a fushi o rodilla)",
  "uchi oshi uke geri (ura & omote)": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote) Atacante: gyaku furi zuki Defensor: tate muso; jun o sokuto geri kaeshi",
  "gedan gaeshi to tobi ni ren geri": "Posicion: hiraki gamae. Atacante: ni ren uke vs geri, keri kaeshi 4dan th",
  "morote okuri gote, baku ho ichi": "Posicion: hiraki gamae. Como en morote maki nuki. Defensor: tsuri age ura gatame, hiza gatame, baku ho ichi",
  "hangetsu gaeshi sukui kubi nage": "Posicion: tai gamae. Atacante: jo chu. Defensor: midari; kumade, hiza geri, sukui kubi nage",
  "chudan gaeshi to uchi uke zuki": "Posicion: hiraki gamae. Defensor: jo chu ren han ko, despues uchi uke zuki",
  "soto uke zuki (omote) renhanko": "Posicion: hiraki gamae. Atacante: jodan gyaku zuki Defensor: ren han ko Como en uwa uke zuki (omote)",
  "keri ten ichi sukui kubi nage": "Posicion: tai gamae. Atacante: jo chu mawashi. Defensor: soto uke, girar, hasami uke",
  "uwa uke zuki (omote) renhanko": "Posicion: tai gamae. Defensor: sashi kae ashi uwa uke, chudan jun zuki, kumade zuki, mas keri ten ichi ren han ko",
  "gyaku gassho nage (two types)": "Posicion: tai gamae. cruzado grip palmas o pulgares",
  "johaku dori (katate & ryote)": "Posicion: tai gamae. Atacante: Como en johaku nuki Defensor: gyaku gedan gamae; ryote: mano adelantada nuki primero",
  "soto uke zuki (ura) renhanko": "Posicion: tai gamae. Atacante: jodan gyaku zuki. Defensor: gyaku soto uke, jun zuki; renhanko Como en uwa uke zuki (ura)",
  "johaku nuki (katate & ryote)": "Posicion: tai gamae. Atacante: agarra uno o ambos brazos por el biceps y empuja Defensor: gyaku gedan gamae",
  "ryote okuri gote, ura gatame": "Posicion: tai gamae. Defensor: despues primero nuki, me uchi, directo a okuri gote, ura gatame",
  "gyakute nage, gyakute gatame": "Posicion: hiraki gamae. Adaptacion de gyaku gote. Atacante: entra cerrando distancia kagite",
  "ude juji, tate gassho gatame": "Posicion: tai gamae. Shikake waza Atacante: luxacion de brazo de pie, proyeccion y control, fumi geri",
  "shita uke zuki (ura & omote)": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote) Defensor: hasso gamae, shita uke, jodan gyaku zuki",
  "gyaku gote, mae yubi gatame": "Posicion: hiraki gamae. Atacante: agarre cruzado por dentro de la muñeca Defensor: atacar dai kento",
  "soto uke geri (ura & omote)": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan gyaku zuki Defensor: gyaku soto uke",
  "uchi age geri (ura & omote)": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan jun zuki Defensor: jun uchi age, jun geri",
  "kiri gote (katate & morote)": "Posicion: hiraki gamae. Como en kiri kaeshi nuki (morote) Defensor: gyaku gedan gamae",
  "suigetsu gaeshi oshi taoshi": "Posicion: tai gamae. Atacante: gyaku zuki. Defensor: taiki; tenchu uchi, derribo al cuerpo",
  "uchi age zuki (ura & omote)": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan gyaku zuki",
  "sode nuki (katate & ryote)": "Posicion: tai gamae. Atacante: agarra una o ambas mangas altas y tira Defensor: gyaku gedan gamae",
  "juji gote (katate & ryote)": "Posicion: hiraki gamae. Atacante: Como en juji nuki Defensor: ryote (tai) no libera primero",
  "ude juji (katame to renko)": "Posicion: tai gamae. Shikake waza Atacante: atacar hakusetsu, luxacion de brazo de pie, conduccion",
  "tanto furi age ryusui geri": "Posicion: tai gamae. Atacante: cuchillada descendente desde arriba. Defensor: aiki; mae ryusui geri",
  "gyaku gote ura gaeshi nage": "Posicion: hiraki gamae. Como en gyaku gote Defensor: proyeccion y control ura gatame",
  "oshi gote (katate & ryote)": "Posicion: hiraki gamae. Como en yori nuki. Atacante: gira hacia dentro a impedir yori nuki Defensor: kannuki gatame",
  "kaishin zuki (ura & omote)": "Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku zuki o jun zuki (tai o hiraki) Defensor: midare g., gyaku hangetsu kakete uke, jun zuki",
  "uchi nuki (katate & ryote)": "Posicion: cualquier kamae indicado. cualquier agarre de muneca por dentro o por fuera, golpea a libera",
  "juji nuki (katate & ryote)": "Posicion: hiraki gamae. ofrece la mano levantada(s) Atacante: mano adelantada(s) agarra por fuera de la muneca(s)",
  "kiri kaeshi nuki (katate)": "Posicion: hiraki gamae. Atacante: agarra la parte superior de la muneca, tira & golpea / gira",
  "katate kiri kaeshi tembin": "Posicion: hiraki gamae. Atacante: empuja alejando directo a resistir kiri gote Defensor: gyaku gedan gamae",
  "morote kiri kaeshi tembin": "Posicion: hiraki gamae. Atacante: empuja alejando directo a resistir kiri gote Defensor: gyaku gedan gamae",
  "kubi jime shuho juji nage": "Posicion: tai gamae. Atacante: estrangulacion. Defensor: shuho; atacar muneca inferior",
  "kiri kaeshi nuki (morote)": "Posicion: hiraki gamae. Atacante: ambas manos agarra la muñeca para detencion / proyeccion",
  "mikazuki gaeshi kari ashi": "Posicion: tai gamae. Atacante: sashi kae jun zuki. Defensor: taiki; kari ashi",
  "okuri gassho (two types)": "Posicion: hiraki gamae. mismo lado grip, dos formas",
  "chudan gaeshi ren han ko": "Posicion: hiraki gamae. Atacante: jun mawashi. Defensor: taiki (abierto); gyaku shita uke",
  "chidori gaeshi kari ashi": "Posicion: tai gamae. Atacante: sashi kae ashi jodan jun zuki",
  "omote uchi oshi uke geri": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote) Atacante: gyaku furi zuki Defensor: tate muso; jun o sokuto geri kaeshi",
  "okuri gassho konoha nage": "Posicion: hiraki gamae. Atacante: shikake waza; pasa por debajo del brazo",
  "shita uke geri kote nage": "Posicion: tai gamae. Como en shita uke geri",
  "ushiro sode maki (dori)": "Posicion: cualquier kamae indicado. Atacante: agarra la manga Desde atras. Defensor: tembin",
  "kiri kaeshi maki tembin": "Posicion: hiraki gamae. Atacante: empuja despues gira hacia fuera a resistir kiri gote Defensor: gyaku gedan gamae",
  "tsubame gaeshi renhanko": "Posicion: hiraki gamae. Atacante: jodan gyaku zuki Defensor: taiki gamae; renhanko",
  "katate nage kiri kaeshi": "Posicion: tai gamae. Atacante: intento de katate nage",
  "hasami daoshi (2 types)": "Posicion: cualquier kamae indicado. Atacante: shikake, sutemi waza; mawashi geri primero",
  "morote kiri kaeshi nage": "Posicion: hiraki gamae. Atacante: intento de hammer proyeccion, detencion. Defensor: gyaku gedan",
  "osae kannuki nage uchi": "Posicion: hiraki gamae. Atacante: gyaku zuki. Defensor: midare, kannuki",
  "uwa uke zuki with nyoi": "Posicion: tai gamae. Defensor: Como en uwa uke zuki (omote)",
  "ura uchi oshi uke geri": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote) Atacante: gyaku furi zuki Defensor: tate muso; jun o sokuto geri kaeshi",
  "gyaku ten ichi (omote)": "Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku, chudan jun zuki Defensor: hiraki (ura), uchi uke, harai uke, geri; tai (omote), hiraki sagari con uchi uke",
  "osae kannuki nage soto": "Posicion: tai gamae. Atacante: gyaku zuki. Defensor: midare; kannuki",
  "morote okuri gote nage": "Posicion: hiraki gamae. Atacante: intento de se nage. Defensor: manji; jun mawashi",
  "fukko daoshi (3 types)": "Posicion: hiraki gamae. Defensor: seiza; atacar san inko, kekkai, yako",
  "uchi uke zuki (omote)": "Posicion: hiraki gamae. Atacante: jodan gyaku zuki Defensor: jun uchi uke, chudan gyaku zuki",
  "juji uke geri (omote)": "Posicion: tai gamae. Atacante: jun mawashi geri Defensor: juji uke, jun o mawashi geri",
  "ashi nuki (two types)": "Posicion: cualquier kamae indicado. Defensor: sokuto geri; empuja alejando o manos hacia abajo",
  "tora daoshi (2 types)": "Posicion: cualquier kamae indicado. Atacante: mawashi geri. Defensor: atrapa la pierna; atacar shokin",
  "uchi uke geri (omote)": "Posicion: hiraki gamae. Atacante: jodan gyaku zuki Defensor: jun uchi uke, jun sokuto geri",
  "okuri hiji zeme omote": "Posicion: hiraki gamae. Defensor: shuto / wanto a elbow",
  "tsuki ten san (omote)": "Posicion: tai gamae. Defensor: gyaku uchi uke, jun shita uke, gyaku uwa uke zuki",
  "omote gyaku ten ichi": "Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku, chudan jun zuki Defensor: hiraki (ura), uchi uke, harai uke, geri; tai (omote), hiraki sagari con uchi uke",
  "omote shita uke zuki": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote) Defensor: hasso gamae, shita uke, jodan gyaku zuki",
  "uwa uke gyakute nage": "Posicion: tai gamae. Atacante: retrocede tirando despues de ura ken. Defensor: gyakute gatame",
  "sode maki gaeshi ura": "Posicion: hiraki gamae. Atacante: agarre cruzado de manga baja. Defensor: gyaku gedan",
  "hiji nuki mae tembin": "Posicion: tai gamae. Atacante: ryote dori, empuja una mano atras. Defensor: usa el cuello",
  "keri ten san (omote)": "Posicion: hiraki gamae. Atacante: jo chu ni ren zuki gyaku mawashi geri",
  "okuri eri dori omote": "Posicion: hiraki gamae. Atacante: agarra la solapa high, by neck",
  "gyaku ten ichi (ura)": "Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku, chudan jun zuki Defensor: hiraki (ura), uchi uke, harai uke, geri; tai (omote), hiraki sagari con uchi uke",
  "sode dori nai tembin": "Posicion: tai gamae. Atacante: agarra la manga. Defensor: gyaku gedan; envuelve el brazo",
  "ushiro bukkotsu nage": "Posicion: cualquier kamae indicado. Atacante: agarra el cuello desde atras & kari ashi",
  "kubi jime nage omote": "Posicion: tai gamae. Atacante: estrangulacion a",
  "katate kumade gaeshi": "Posicion: hiraki gamae. entrelaza los dedos. Defensor: maki (‘lose’ kumade) o dori",
  "furi sute omote nage": "Posicion: hiraki gamae. Atacante: intento de ippon se nage. Defensor: manji; una mano",
  "ryu nage, ryu gatame": "Posicion: hiraki gamae. Adaptacion de gyaku gote. Atacante: extendido kagite",
  "maki uchi kubi nage": "Posicion: tai gamae. Atacante: agarre tipo judo, tira. Defensor: nai wanto a tenchu",
  "gyaku geri chi ichi": "Posicion: hiraki gamae. Atacante: toride zuki gyaku kinteki geri. Defensor: Como en jun",
  "hagai jime to shuho": "Posicion: ataque desde atras. Atacante: empuja head hacia abajo Desde atras",
  "tsuki ten san (ura)": "Posicion: hiraki gamae. Atacante: jo chu jo san ren zuki",
  "harai bukkotsu nage": "Posicion: tai gamae. Atacante: empuja alejando a resistir bukkotsu",
  "uchi uke zuki (ura)": "Posicion: tai gamae. Atacante: jodan gyaku zuki Defensor: uchi uke, chudan gyaku zuki a suigetsu",
  "omote uchi age zuki": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan gyaku zuki",
  "gyaku konoha gaeshi": "Posicion: tai gamae. Atacante: shikake waza; Desde saludo de manos",
  "uchi uke geri (ura)": "Posicion: tai gamae. Atacante: jodan gyaku zuki Defensor: jun uchi uke, jun sokuto geri",
  "omote kumade gaeshi": "Posicion: hiraki gamae. Defensor: 'win' kumade gaeshi; atacar kokoku, ura taoshi",
  "gassho tsuki otoshi": "Posicion: tai gamae. Atacante: Desde gassho choji, o directo away",
  "katate kannuki nage": "Posicion: tai gamae. Atacante: shikake waza; empuja hacia arriba under dai kento",
  "omote soto uke geri": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan gyaku zuki Defensor: gyaku soto uke",
  "omote uchi age geri": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan jun zuki Defensor: jun uchi age, jun geri",
  "kannuki katate nage": "Posicion: tai gamae. Atacante: shikake waza; kannuki primero",
  "kannuki soto tembin": "Posicion: hiraki gamae. Atacante: tembin cuando kannuki okuri falla",
  "nuki uchi oshi gote": "Posicion: tai gamae. Atacante: agarra ambas muñecas, gira hacia dentro. Defensor: nuki primero",
  "ryote kumade gaeshi": "Posicion: tai gamae. ambas manos",
  "hangetsu kubi nage": "Posicion: tai gamae. Atacante: furi zuki. Defensor: nai wanto a tenchu, hook",
  "oshi uke maki nage": "Posicion: tai gamae. Atacante: furi zuki, retrocede tirando",
  "shita uke dan zuki": "Posicion: tai gamae. Defensor: ura ken tsuki komi a jinchu o nichigetsu",
  "ushiro ryusui geri": "Posicion: tai gamae. Atacante: jodan gyaku zuki Defensor: nio gamae; ryusui uke a rear, jun geri, juji ashi",
  "ryote kannuki nage": "Posicion: tai gamae. Atacante: shikake waza",
  "omote kaishin zuki": "Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku zuki o jun zuki (tai o hiraki) Defensor: midare g., gyaku hangetsu kakete uke, jun zuki",
  "keri ten san (ura)": "Posicion: tai gamae. Defensor: gyaku uchi uke, jun shita uke, girar para juji uke geri",
  "gyaku geri chi san": "Posicion: tai gamae. Atacante: gyaku kinteki, jun shuto giri chudan zuki",
  "katate johaku dori": "Posicion: tai gamae. Atacante: Como en johaku nuki Defensor: gyaku gedan gamae; ryote: mano adelantada nuki primero",
  "gyaku tenshin geri": "Posicion: hiraki gamae. Atacante: sashi kae ashi chudan jun zuki Defensor: hasso gamae",
  "maki nuki (katate)": "Posicion: hiraki gamae. Como en yori nuki Atacante: gira la mano hacia fuera para resistir yori nuki",
  "gassho katate nage": "Posicion: tai gamae. Atacante: saludo de manos",
  "harai uke dan zuki": "Posicion: hiraki gamae. Defensor: ura ken tsuki komi o ura ken uchi a sango",
  "uwa uke zuki (ura)": "Posicion: tai gamae. Atacante: gyaku shuto uchi Defensor: gyaku uwa uke, chudan jun zuki",
  "ura shita uke zuki": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote) Defensor: hasso gamae, shita uke, jodan gyaku zuki",
  "uchi oshi uke zuki": "Posicion: hiraki gamae. Atacante: gyaku furi zuki",
  "yori nuki (katate)": "Posicion: hiraki gamae. Atacante: agarre del mismo lado por fuera de la muñeca Defensor: kumade zuki a mikazuki",
  "okuri tsuki taoshi": "Posicion: hiraki gamae. Atacante: intento de se nage. Defensor: manji; chudan jun zuki",
  "kannuki okuri dori": "Posicion: hiraki gamae. Atacante: shikake; kannuki gatame",
  "okuri kannuki gote": "Posicion: hiraki gamae. Atacante: Como en tsuki nuki (empuja hacia abajo)",
  "shikumi koshi nage": "Posicion: tai gamae. agarre tipo sumo. Defensor: hiza geri, koshi nage",
  "ura gyaku ten ichi": "Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku, chudan jun zuki Defensor: hiraki (ura), uchi uke, harai uke, geri; tai (omote), hiraki sagari con uchi uke",
  "kannuki nai tembin": "Posicion: hiraki gamae. Defensor: midare gamae",
  "shita uke jun geri": "Posicion: tai gamae. Atacante: chudan jun zuki Defensor: hasso gamae, gyaku shita uke, jun geri",
  "morote katate nage": "Posicion: cualquier kamae indicado. Atacante: intento de ippon se nage o gyaku tembin",
  "katate johaku nuki": "Posicion: tai gamae. Atacante: agarra uno o ambos brazos por el biceps y empuja Defensor: gyaku gedan gamae",
  "soto oshi uke geri": "Posicion: tai gamae. Atacante: jodan gyaku furi zuki",
  "gassho hiki tembin": "Posicion: tai gamae. Desde saludo de manos",
  "soto oshi uke zuki": "Posicion: tai gamae. Atacante: gyaku furi zuki Defensor: sashi kae ashi soto oshi uke; kumade zuki",
  "shikumi nai tembin": "Posicion: tai gamae. agarre tipo sumo. Defensor: hiza geri, tembin",
  "gyaku katate nage": "Posicion: cualquier kamae indicado. Atacante: Como en gyaku gote",
  "soto gyakute dori": "Posicion: cualquier kamae indicado. Shikake o Desde kote nage, omote",
  "uchi gyakute dori": "Posicion: cualquier kamae indicado. Shikake o Desde kote nage, ura",
  "ryote johaku dori": "Posicion: tai gamae. Atacante: Como en johaku nuki Defensor: gyaku gedan gamae; ryote: mano adelantada nuki primero",
  "ryote katate nage": "Posicion: tai gamae. Atacante: ryote agarra",
  "soto uke dan zuki": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Defensor: tate muso gamae; mano adelantada cover uchi uke",
  "okuri katate nage": "Posicion: hiraki gamae. Atacante: Como en yori nuki",
  "gyaku gassho nage": "Posicion: tai gamae. cruzado grip palmas o pulgares",
  "tsuki nuki (soto)": "Posicion: hiraki gamae. Como en yori nuki. Atacante: empuja hacia abajo Defensor: tsuitate shuho, kinteki uchi",
  "kusshin zuki geri": "Posicion: tai gamae. Defensor: chudan gyaku zuki followed by gyaku (mawashi) geri",
  "gassho gyaku gote": "Posicion: cualquier kamae indicado. Defensor: 'tate ichiji' cuando gyaku gote falla",
  "tsuki nuki (uchi)": "Posicion: hiraki gamae. Como en kote nuki. Atacante: empuja hacia abajo Defensor: tsuitate shuho, kinteki uchi",
  "katate okuri gote": "Posicion: hiraki gamae. Como en maki nuki Defensor: yubi dori renko",
  "morote gyaku gote": "Posicion: hiraki gamae. Como en wa nuki. Defensor: tate ichiji gatame, sekoshi ichiji gatame (con uchi uke geri), kumo garami",
  "okuri shishi dori": "Posicion: hiraki gamae. Como en okuri gote. Atacante: suelta el agarre",
  "gassho okuri dori": "Posicion: hiraki gamae. Como en okuri gote. Atacante: gira hacia fuera under",
  "morote tsuki nuki": "Posicion: tai gamae. Atacante: dos manos agarra un brazo, empuja hacia abajo Defensor: kinteki uchi, hiji ate",
  "yoko tenshin geri": "Posicion: tai gamae. Atacante: ichiji gamae; gyaku geri Defensor: chudan gamae; jun uchi harai uke, jun geri",
  "ryote johaku nuki": "Posicion: tai gamae. Atacante: agarra uno o ambos brazos por el biceps y empuja Defensor: gyaku gedan gamae",
  "okuri yubi gaeshi": "Posicion: hiraki gamae. Atacante: intento de konoha atacar",
  "okuri tembin dori": "Posicion: hiraki gamae. 1: shikake waza. 2: Desde okuri gote. atacar chuin.",
  "gyaku hiki tembin": "Posicion: cualquier kamae indicado. Como en gyaku gote. Atacante: empuja alejando",
  "jun geri chi ichi": "Posicion: tai gamae. Atacante: hebite zuki jun kinteki geri. Defensor: yoko muso; ken uke a taisho",
  "ura uchi age geri": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan jun zuki Defensor: jun uchi age, jun geri",
  "ura uchi age zuki": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan gyaku zuki",
  "okuri maki tembin": "Posicion: hiraki gamae. Como en okuri gote Atacante: gira hacia fuera a escapar de okuri gote",
  "ura soto uke geri": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan gyaku zuki Defensor: gyaku soto uke",
  "uchi age dan zuki": "Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Defensor: mano adelantada cover uchi uke",
  "kiri nuki (soto)": "Posicion: hiraki gamae. Ofrece levantada mano adelantada Atacante: agarra por fuera de la muneca, tira",
  "sode maki tembin": "Posicion: tai gamae. Como en sode maki. Atacante: gira hacia fuera a escapar de sode maki",
  "ushiro kubi nage": "Posicion: cualquier kamae indicado. Atacante: agarra el cuello desde atras. Defensor: girar, envuelve el brazo",
  "kiri nuki (uchi)": "Posicion: tai gamae. Ofrece levantada mano adelantada Atacante: agarra por dentro de la muneca, tira",
  "morote juji nuki": "Posicion: tai gamae. ofrece la mano levantada Atacante: ambas manos agarra la muñeca & empuja",
  "sode maki gaeshi": "Posicion: tai gamae. Atacante: agarra la manga, ashi barai. Defensor: aiki gamae",
  "katate uchi nuki": "Posicion: cualquier kamae indicado. cualquier agarre de muneca por dentro o por fuera, golpea a libera",
  "katate kiri gote": "Posicion: hiraki gamae. Como en kiri kaeshi nuki (morote) Defensor: gyaku gedan gamae",
  "katate maki gote": "Posicion: tai gamae. Como en kiri nuki (uchi)",
  "morote juji gote": "Posicion: tai gamae. ofrece la mano levantada Atacante: ambas manos agarra la muñeca & empuja",
  "morote kiri gote": "Posicion: hiraki gamae. Como en kiri kaeshi nuki (morote) Defensor: gyaku gedan gamae",
  "idori okuri gote": "Posicion: hiraki gamae. Defensor: seiza; kuzushi, fukko; okuri yoko tembin, ura gatame",
  "katate oshi gote": "Posicion: tai gamae. Atacante: agarra ambas muñecas, gira hacia dentro. Defensor: nuki primero",
  "ura kaishin zuki": "Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku zuki o jun zuki (tai o hiraki) Defensor: midare g., gyaku hangetsu kakete uke, jun zuki",
  "morote oshi nuki": "Posicion: tai gamae. Defensor: manji gamae; defensa contra gyaku tembin",
  "morote hiki nuki": "Posicion: tai gamae. Atacante: intento de ude gyaku dori (maki tembin), both",
  "kata muna otoshi": "Posicion: hiraki gamae. Atacante: agarra la solapa alta, puno vertical",
  "katate sode nuki": "Posicion: tai gamae. Atacante: agarra una o ambas mangas altas y tira Defensor: gyaku gedan gamae",
  "harai uke chi ni": "Posicion: hiraki gamae. Atacante: jun mawashi, gyaku zuki. Defensor: kesshu",
  "katate oshi nuki": "Posicion: tai gamae. Atacante: agarra la parte inferior de la muneca Defensor: gyaku gedan gamae",
  "kiri kaeshi gote": "Posicion: hiraki gamae. Como en kiri gote. Atacante: suelta el agarre. Defensor: gyaku gedan",
  "ryote tsuki nuki": "Posicion: tai gamae. Como en ryote yori nuki Defensor: tsuitate shuho, kinteki uchi, hiji ate",
  "jun geri chi san": "Posicion: hiraki gamae. Atacante: jun sokuto, jo chu ni ren zuki",
  "kiri kaeshi nage": "Posicion: hiraki gamae. Como en kiri gote. Atacante: suelta el agarre. Defensor: gyaku gedan; ura gassho gatame",
  "han tenshin geri": "Posicion: hiraki gamae. Atacante: ichiji gamae; gyaku geri Defensor: chudan gamae; uchi otoshi uke, jun geri",
  "kote maki gaeshi": "Posicion: tai gamae. Como en katate oshi nuki Defensor: gyaku gedan gamae; atacar sunmyaku, kannuki gatame",
  "katate juji nuki": "Posicion: tai gamae. ofrece la mano levantada Atacante: ambas manos agarra la muñeca & empuja",
  "soto maki otoshi": "Posicion: tai gamae. Atacante: Como en maki otoshi, empuja. Defensor: gyaku gedan gamae",
  "idori gyaku gote": "Posicion: hiraki gamae. Defensor: seiza; kuzushi, fukko; osae yubi gatame",
  "soto maki tembin": "Posicion: hiraki gamae. Adaptacion de gyaku gote. Atacante: empuja alejando",
  "hiki muna otoshi": "Posicion: tai gamae. Atacante: agarra la solapa. Defensor: aiki; usa una mano",
  "katate juji gote": "Posicion: hiraki gamae. Como en sei juji gote, pero ofrece la mano baja",
  "morote maki nuki": "Posicion: hiraki gamae. Atacante: intento de se nage. Defensor: jun mawashi atemi",
  "ryo muna otoshi": "Posicion: tai gamae. Atacante: agarra ambas solapas. Defensor: aiki; golpea sumyaku",
  "gyaku sode dori": "Posicion: cualquier kamae indicado. Atacante: cruzado agarra la manga (alta). Defensor: gyaku waza",
  "gyaku sode maki": "Posicion: cualquier kamae indicado. Atacante: cruzado agarra la manga (baja). Defensor: envuelve el brazo",
  "ryote uchi nuki": "Posicion: cualquier kamae indicado. cualquier agarre de muneca por dentro o por fuera, golpea a libera",
  "ryote juji gote": "Posicion: hiraki gamae. Como en sei juji gote, pero ofrece la mano baja",
  "ryote juji nuki": "Posicion: tai gamae. ofrece la mano levantada Atacante: ambas manos agarra la muñeca & empuja",
  "ryote maki nuki": "Posicion: tai gamae. Como en ryote yori nuki Defensor: segunda salida yori nuki",
  "sode guchi maki": "Posicion: hiraki gamae. Atacante: agarra la manga bocamanga, pulgar por dentro. Defensor: aiki",
  "ryaku juji gote": "Posicion: hiraki gamae. Como en sei juji gote, pero ofrece la mano baja",
  "ryote sode nuki": "Posicion: tai gamae. Atacante: agarra una o ambas mangas altas y tira Defensor: gyaku gedan gamae",
  "ryote yori nuki": "Posicion: tai gamae. Atacante: agarra ambas muñecas Defensor: me uchi chudan dan zuki",
  "sode guchi dori": "Posicion: hiraki gamae. Atacante: agarra la manga bocamanga, dedos por dentro. Defensor: aiki",
  "mae ryusui geri": "Posicion: tai gamae. Atacante: gyaku shuto uchi Defensor: nio gamae; mae ryusui uke, gyaku geri",
  "uwa uke se nage": "Posicion: tai gamae. Atacante: ura ken tsuki komi o shuto uchi. Defensor: jun zuki",
  "ryote oshi gote": "Posicion: tai gamae. Atacante: agarra ambas muñecas, gira hacia dentro. Defensor: nuki primero",
  "idori oshi gote": "Posicion: hiraki gamae. Defensor: seiza; kuzushi, fukko; kannuki gatame",
  "okuri hiji zeme": "Posicion: hiraki gamae. Atacante: levanta el codo a escapar de okuri gote",
  "ushiro eri dori": "Posicion: cualquier kamae indicado. Atacante: agarra el cuello desde atras, kari ashi",
  "kubi jime nage": "Posicion: tai gamae. Atacante: estrangulacion con top arm. Defensor: se nage",
  "okuri eri dori": "Posicion: hiraki gamae. Atacante: agarra la solapa alta cerca del cuello. Defensor: aiki gamae",
  "kata uchi nage": "Posicion: hiraki gamae. Atacante: agarra la manga o muneca para kata guruma proyeccion",
  "tsuki ten ichi": "Posicion: hiraki gamae. Atacante: jo chu ni ren zuki Defensor: ni ren uke, jun geri",
  "gyakute gatame": "Posicion: hiraki gamae. Adaptacion de gyaku gote. Atacante: entra cerrando distancia kagite",
  "tsuri age dori": "Posicion: tai gamae. Atacante: shikake waza; agarra primero la muñeca",
  "shita uke geri": "Posicion: tai gamae. Atacante: chudan gyaku zuki Defensor: hasso gamae; jun shita uke, gyaku geri",
  "maki komi gote": "Posicion: tai gamae. Atacante: Como en sankaku nuki",
  "oshi kiri nuki": "Posicion: tai gamae. Como en ryote johaku nuki",
  "maki juji gote": "Posicion: hiraki gamae. Como en sei juji gote o ryaku juji gote",
  "harai uke geri": "Posicion: hiraki gamae. Atacante: jun mawashi geri Defensor: nio gamae; kokutsu dachi, gyaku geri",
  "morote wa nuki": "Posicion: hiraki gamae. Atacante: intento de se nage, codos hacia fuera",
  "hasami daoshi": "Posicion: cualquier kamae indicado. Atacante: shikake, sutemi waza; mawashi geri primero",
  "nigiri gaeshi": "Posicion: tai gamae. Atacante: saludo de manos & aprieta. Defensor: ura gassho gatame 3dan rd",
  "bukkotsu nage": "Posicion: tai gamae. Atacante: agarre tipo judo (aiyotsu, solapa alta y manga)",
  "mae gami dori": "Posicion: cualquier kamae indicado. Atacante: agarra el pelo desde delante",
  "oshi uke nage": "Posicion: tai gamae. Atacante: furi zuki. Defensor: kakete uke",
  "hangetsu geri": "Posicion: tai gamae. Atacante: gyaku zuki. Defensor: midare; hangetsu kakete uke",
  "konoha gaeshi": "Posicion: hiraki gamae. Atacante: shikake waza",
  "gyakute nage": "Posicion: tai gamae. Atacante: retrocede tirando despues de ura ken. Defensor: gyakute gatame",
  "uwa uke geri": "Posicion: tai gamae. & Hiraki Atacante: gyaku shuto uchi Defensor: jun uwa uke, jun geri",
  "gassho choji": "Posicion: tai gamae. Atacante: shikake waza; choji a yokei",
  "kon ten ichi": "Posicion: hiraki gamae. Atacante: jun furi zuki, chudan gyaku choku zuki",
  "kusshin zuki": "Posicion: tai gamae. Atacante: furi zuki Defensor: kusshin, jun uchi age uke, gyaku zuki",
  "fukko daoshi": "Posicion: hiraki gamae. Defensor: seiza; atacar san inko, kekkai, yako",
  "uwa uke nage": "Posicion: tai gamae. Atacante: ura ken uchi. Defensor: kakete uke; kannuki gatame",
  "tenshin geri": "Posicion: tai gamae. Atacante: jodan gyaku zuki Defensor: kani ashi, gyaku geri",
  "konoha choji": "Posicion: tai gamae. Atacante: shikake waza; cruzado agarra, ura taoshi",
  "gedan gaeshi": "Posicion: hiraki gamae. Atacante: jun mawashi geri Defensor: zenkutsu dachi, jun geri",
  "fukko chi ni": "Posicion: hiraki gamae. Atacante: jun mawashi, gyaku zuki. Defensor: seiza; bloquea kori",
  "koshi kujiki": "Posicion: hiraki gamae. Atacante: intento de se nage. Defensor: manji; golpea chokyu",
  "tai ten ichi": "Posicion: tai gamae. Atacante: jo chu. Defensor: gyaku uwa uke, jun shita uke",
  "tsuri otoshi": "Posicion: hiraki gamae. Como en maki tembin. Defensor: proyeccion away",
  "sankaku nuki": "Posicion: hiraki gamae. Atacante: 'hammer' proyeccion o detencion Defensor: gyaku gedan gamae, sankaku shuho",
  "kusshin geri": "Posicion: tai gamae. Como en kusshin zuki, pero distancia mas amplia Defensor: gyaku geri",
  "okuri gassho": "Posicion: hiraki gamae. mismo lado grip, dos formas",
  "kenjime dori": "Posicion: tai gamae. Atacante: atacar",
  "tsuki ten ni": "Posicion: hiraki gamae. Atacante: jo jo ni ren zuki Defensor: jun uchi age uchi otoshi dan uke, jun geri",
  "gyaku tembin": "Posicion: tai gamae. Shikake waza. Atacante: dos manos agarra para luxacion de codo",
  "konoha okuri": "Posicion: hiraki gamae. Atacante: shikake waza; konoha gatame",
  "furi ten ni": "Posicion: hiraki gamae. Atacante: jodan jun furi zuki, chudan gyaku furi zuki Defensor: sokuto geri",
  "yahazu nage": "Posicion: cualquier kamae indicado. Atacante: abrazo desde atras Desde atras. Defensor: yahazu shuho, kinteki uchi",
  "hiki tembin": "Posicion: tai gamae. Atacante: shikake waza; golpea gori",
  "gassho nuki": "Posicion: tai gamae. Como en kiri nuki Atacante: agarra ambas manos y tira",
  "maki otoshi": "Posicion: tai gamae. Atacante: agarra la solapa & tira, golpea. Defensor: gyaku gedan gamae",
  "tora daoshi": "Posicion: cualquier kamae indicado. Atacante: mawashi geri. Defensor: atrapa la pierna; atacar shokin",
  "tekubi dori": "Posicion: tai gamae. Atacante: agarra la solapa & empuja con palma",
  "tembin nage": "Posicion: tai gamae. Defensor: Desde hangetsu geri",
  "katate nage": "Posicion: tai gamae. Atacante: shikake waza",
  "johaku maki": "Posicion: tai gamae. Atacante: agarra el biceps Desde lado, y empuja Defensor: gyaku gedan gamae",
  "hiki otoshi": "Posicion: tai gamae. Como en johaku dori",
  "okuri dori": "Posicion: tai gamae. Atacante: shikake waza; pasa caminando & agarra la muñeca",
  "nidan nuki": "Posicion: tai gamae. Como en ryote yori nuki Atacante: gira ambas manos inwards",
  "omote nage": "Posicion: hiraki gamae. Atacante: intento de ippon se nage. Defensor: manji; una mano",
  "ninin nuki": "Posicion: cualquier kamae indicado. dos atacantes, cada uno agarra un brazo y tira 2dan nd",
  "machi geri": "Posicion: cualquier kamae indicado. Atacante: cualquier golpe de puño. Defensor: yoko muso gamae; jun geri",
  "choji dori": "Posicion: tai gamae. Atacante: Como en tekubi dori, tira hacia abajo. Defensor: atacar chusho",
  "choji nage": "Posicion: tai gamae. Como en ryote kannuki nage",
  "kote nuki": "Posicion: hiraki gamae. Atacante: agarre cruzado por dentro de la muñeca Defensor: uraken uchi a sango/yongo",
  "ashi nuki": "Posicion: cualquier kamae indicado. Defensor: sokuto geri; empuja alejando o manos hacia abajo",
  "sode juji": "Posicion: hiraki gamae. ofrece la mano levantada. Atacante: agarra la manga",
  "sode maki": "Posicion: tai gamae. Como en sode nuki. Atacante: agarra atras de alta manga Defensor: gyaku gedan gamae",
  "sode dori": "Posicion: tai gamae. Como en sode nuki. Atacante: agarra alta manga & tira",
  "eri nuki": "Posicion: tai gamae. Atacante: agarra la solapa baja o la chaqueta Defensor: gyaku gedan gamae",
  "ryu nage": "Posicion: hiraki gamae. Adaptacion de gyaku gote. Atacante: extendido kagite",
  "age nuki": "Posicion: hiraki gamae. Atacante: empuja a muslo o pecho. Defensor: seiza o de pie",
  "ude maki": "Posicion: tai gamae. Como en eri nuki. Atacante: agarra la solapa baja o la chaqueta",
  "ura nage": "Posicion: tai gamae. Defensor: cambia la direccion cuando omote falla",
  "eri juji": "Posicion: hiraki gamae. Atacante: agarra la solapa alta, puno horizontal Defensor: golpea hacia arriba con nai wanto",
  "obi dori": "Posicion: cualquier kamae indicado. Atacante: agarra el cinturon palma hacia abajo, o palma hacia arriba"
};

export function getKamokuSummaryFallback(name: string | null | undefined) {
  const key = normalizeKamokuKey(name);
  if (!key) return "";
  return kamokuSummaryFallbacks[key] ?? kamokuSummaryFallbacks[stripKamokuVariantKey(key)] ?? "";
}

export function normalizeKamokuKey(value: string | null | undefined) {
  return String(value ?? "").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\s+/g, " ");
}

function stripKamokuVariantKey(key: string) {
  return key
    .replace(/^(katate|morote|ryote|ura|omote) /, "")
    .replace(/ \((ura|omote|katate|ryote|two types|3 types)\)/g, "")
    .replace(/\s+/g, " ")
    .trim();
}
