-- Seed inicial del programa infantil editable.
-- Origen: temario usado por el examen progresivo infantil del sistema antiguo de examenes.
-- Se copia al sistema nuevo para poder crear examenes infantiles integrados sin depender del sistema viejo.

insert into public.child_syllabus_items (
  grade,
  title,
  category,
  description,
  exam_relevant,
  active,
  sort_order,
  created_by
)
values
  ('5 KYU', 'Chudan gamae', 'tai_gamae', 'Copiado del examen progresivo infantil antiguo. Bloque original: Tai gamae. Base kamoku: 5 KYU.', true, true, 1, 'LEGACY EXAMENES'),
  ('5 KYU', 'Ichiji gamae', 'tai_gamae', 'Copiado del examen progresivo infantil antiguo. Bloque original: Tai gamae. Base kamoku: 5 KYU.', true, true, 2, 'LEGACY EXAMENES'),
  ('5 KYU', 'Hiraki gamae', 'tai_gamae', 'Copiado del examen progresivo infantil antiguo. Bloque original: Tai gamae. Base kamoku: 5 KYU.', true, true, 3, 'LEGACY EXAMENES'),
  ('5 KYU', 'Chidori ashi', 'umpo_ho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Umpo ho. Base kamoku: 5 KYU.', true, true, 4, 'LEGACY EXAMENES'),
  ('5 KYU', 'Kani ashi', 'umpo_ho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Umpo ho. Base kamoku: 5 KYU.', true, true, 5, 'LEGACY EXAMENES'),
  ('5 KYU', 'Kumo ashi', 'umpo_ho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Umpo ho. Base kamoku: 5 KYU.', true, true, 6, 'LEGACY EXAMENES'),
  ('5 KYU', 'Juji ashi', 'umpo_ho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Umpo ho. Base kamoku: 5 KYU.', true, true, 7, 'LEGACY EXAMENES'),
  ('5 KYU', 'Sashi komi ashi', 'umpo_ho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Umpo ho. Base kamoku: 5 KYU.', true, true, 8, 'LEGACY EXAMENES'),
  ('5 KYU', 'Zen tenkan', 'umpo_ho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Umpo ho. Base kamoku: 5 KYU.', true, true, 9, 'LEGACY EXAMENES'),
  ('5 KYU', 'Han tenkan', 'umpo_ho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Umpo ho. Base kamoku: 5 KYU.', true, true, 10, 'LEGACY EXAMENES'),
  ('5 KYU', 'Daisharin', 'ukemi', 'Copiado del examen progresivo infantil antiguo. Bloque original: Ukemi. Base kamoku: 5 KYU.', true, true, 11, 'LEGACY EXAMENES'),
  ('5 KYU', 'Yoko ukemi', 'ukemi', 'Copiado del examen progresivo infantil antiguo. Bloque original: Ukemi. Base kamoku: 5 KYU.', true, true, 12, 'LEGACY EXAMENES'),
  ('5 KYU', 'Tenchiken dai ichi', 'kata_tanen', 'Copiado del examen progresivo infantil antiguo. Bloque original: Kata tan-en. Base kamoku: 5 KYU.', true, true, 13, 'LEGACY EXAMENES'),
  ('5 KYU', 'Ryuo ken dai ichi', 'kata_tanen', 'Copiado del examen progresivo infantil antiguo. Bloque original: Kata tan-en. Base kamoku: 5 KYU.', true, true, 14, 'LEGACY EXAMENES'),
  ('5 KYU', 'Suigetsu', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 5 KYU.', true, true, 15, 'LEGACY EXAMENES'),
  ('5 KYU', 'Mikazuki', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 5 KYU.', true, true, 16, 'LEGACY EXAMENES'),
  ('5 KYU', 'Hakusetsu', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 5 KYU.', true, true, 17, 'LEGACY EXAMENES'),
  ('5 KYU', 'Uchi uke zuki (ura)', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 5 KYU.', true, true, 18, 'LEGACY EXAMENES'),
  ('5 KYU', 'Yori nuki (katate)', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 5 KYU.', true, true, 19, 'LEGACY EXAMENES'),
  ('5 KYU', 'Tenshin geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 5 KYU.', true, true, 20, 'LEGACY EXAMENES'),
  ('5 KYU', 'Kote nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 5 KYU.', true, true, 21, 'LEGACY EXAMENES'),
  ('5 KYU', 'Uwa uke zuki (ura)', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 5 KYU.', true, true, 22, 'LEGACY EXAMENES'),
  ('5 KYU', 'Gyaku gote, mae yubi gatame', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 5 KYU.', true, true, 23, 'LEGACY EXAMENES'),
  ('5 KYU', 'Uwa uke geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 5 KYU.', true, true, 24, 'LEGACY EXAMENES'),
  ('5 KYU', 'Ude juji (katame to renko)', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 5 KYU.', true, true, 25, 'LEGACY EXAMENES'),
  ('5 KYU', 'Gentei goho (single attacks)', 'randori', 'Copiado del examen progresivo infantil antiguo. Bloque original: Randori. Base kamoku: 5 KYU.', true, true, 26, 'LEGACY EXAMENES'),
  ('5 KYU', 'Dokun (recitar Seiku y Seigan)', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 5 KYU.', true, true, 27, 'LEGACY EXAMENES'),
  ('5 KYU', 'Cómo comportarse en el dojo', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 5 KYU.', true, true, 28, 'LEGACY EXAMENES'),
  ('5 KYU', 'Cómo sentarse y respirar durante zazen', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 5 KYU.', true, true, 29, 'LEGACY EXAMENES'),
  ('5 KYU', 'Lista de vocabulario 1', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 5 KYU.', true, true, 30, 'LEGACY EXAMENES'),
  ('4 KYU', 'Gedan gamae', 'tai_gamae', 'Copiado del examen progresivo infantil antiguo. Bloque original: Tai gamae. Base kamoku: 4 KYU.', true, true, 1, 'LEGACY EXAMENES'),
  ('4 KYU', 'Gyaku gedan gamae', 'tai_gamae', 'Copiado del examen progresivo infantil antiguo. Bloque original: Tai gamae. Base kamoku: 4 KYU.', true, true, 2, 'LEGACY EXAMENES'),
  ('4 KYU', 'Hasso gamae', 'tai_gamae', 'Copiado del examen progresivo infantil antiguo. Bloque original: Tai gamae. Base kamoku: 4 KYU.', true, true, 3, 'LEGACY EXAMENES'),
  ('4 KYU', 'Sashi kae ashi', 'umpo_ho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Umpo ho. Base kamoku: 4 KYU.', true, true, 4, 'LEGACY EXAMENES'),
  ('4 KYU', 'Fumi komi ashi', 'umpo_ho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Umpo ho. Base kamoku: 4 KYU.', true, true, 5, 'LEGACY EXAMENES'),
  ('4 KYU', 'Zen tenkan & han tenkan from kesshu gamae', 'umpo_ho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Umpo ho. Base kamoku: 4 KYU.', true, true, 6, 'LEGACY EXAMENES'),
  ('4 KYU', 'Ushiro ukemi', 'ukemi', 'Copiado del examen progresivo infantil antiguo. Bloque original: Ukemi. Base kamoku: 4 KYU.', true, true, 7, 'LEGACY EXAMENES'),
  ('4 KYU', 'Giwa ken dai ichi', 'kata_tanen', 'Copiado del examen progresivo infantil antiguo. Bloque original: Kata tan-en. Base kamoku: 4 KYU.', true, true, 8, 'LEGACY EXAMENES'),
  ('4 KYU', 'Tenchi ken dai ichi', 'kata_sotai', 'Copiado del examen progresivo infantil antiguo. Bloque original: Kata sotai. Base kamoku: 4 KYU.', true, true, 9, 'LEGACY EXAMENES'),
  ('4 KYU', 'Ryuo ken dai ichi', 'kata_sotai', 'Copiado del examen progresivo infantil antiguo. Bloque original: Kata sotai. Base kamoku: 4 KYU.', true, true, 10, 'LEGACY EXAMENES'),
  ('4 KYU', 'Mae zanmai', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 4 KYU.', true, true, 11, 'LEGACY EXAMENES'),
  ('4 KYU', 'Yoko zanmai', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 4 KYU.', true, true, 12, 'LEGACY EXAMENES'),
  ('4 KYU', 'Shin-e', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 4 KYU.', true, true, 13, 'LEGACY EXAMENES'),
  ('4 KYU', 'Hyaku-e', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 4 KYU.', true, true, 14, 'LEGACY EXAMENES'),
  ('4 KYU', 'Mae ryusui geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 4 KYU.', true, true, 15, 'LEGACY EXAMENES'),
  ('4 KYU', 'Maki nuki (katate)', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 4 KYU.', true, true, 16, 'LEGACY EXAMENES'),
  ('4 KYU', 'Shita uke geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 4 KYU.', true, true, 17, 'LEGACY EXAMENES'),
  ('4 KYU', 'Ryote yori nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 4 KYU.', true, true, 18, 'LEGACY EXAMENES'),
  ('4 KYU', 'Tsuki ten ichi', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 4 KYU.', true, true, 19, 'LEGACY EXAMENES'),
  ('4 KYU', 'Katate Johaku nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 4 KYU.', true, true, 20, 'LEGACY EXAMENES'),
  ('4 KYU', 'Ryote Johaku nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 4 KYU.', true, true, 21, 'LEGACY EXAMENES'),
  ('4 KYU', 'Juji uke geri (omote)', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 4 KYU.', true, true, 22, 'LEGACY EXAMENES'),
  ('4 KYU', 'Katate Johaku dori', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 4 KYU.', true, true, 23, 'LEGACY EXAMENES'),
  ('4 KYU', 'Ryote Johaku dori', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 4 KYU.', true, true, 24, 'LEGACY EXAMENES'),
  ('4 KYU', 'Uwa uke zuki (omote) renhanko', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 4 KYU.', true, true, 25, 'LEGACY EXAMENES'),
  ('4 KYU', 'Katate Sode nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 4 KYU.', true, true, 26, 'LEGACY EXAMENES'),
  ('4 KYU', 'Ryote Sode nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 4 KYU.', true, true, 27, 'LEGACY EXAMENES'),
  ('4 KYU', 'Gentei goho (combinations)', 'randori', 'Copiado del examen progresivo infantil antiguo. Bloque original: Randori. Base kamoku: 4 KYU.', true, true, 28, 'LEGACY EXAMENES'),
  ('4 KYU', 'Gentei juho (single grabs)', 'randori', 'Copiado del examen progresivo infantil antiguo. Bloque original: Randori. Base kamoku: 4 KYU.', true, true, 29, 'LEGACY EXAMENES'),
  ('4 KYU', 'Dokun (recitar Shinjo)', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 4 KYU.', true, true, 30, 'LEGACY EXAMENES'),
  ('4 KYU', 'Elementos básicos para principiantes', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 4 KYU.', true, true, 31, 'LEGACY EXAMENES'),
  ('4 KYU', 'La naturaleza única del Shorinji Kempo', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 4 KYU.', true, true, 32, 'LEGACY EXAMENES'),
  ('4 KYU', 'Lista de vocabulario 2', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 4 KYU.', true, true, 33, 'LEGACY EXAMENES'),
  ('4 KYU', 'Kumi embu list 1: select option A or B and perform with a partner, following taikai rules', 'embu', 'Copiado del examen progresivo infantil antiguo. Bloque original: Embu. Base kamoku: 4 KYU.', true, true, 34, 'LEGACY EXAMENES'),
  ('3 KYU', 'Taiki gamae', 'tai_gamae', 'Copiado del examen progresivo infantil antiguo. Bloque original: Tai gamae. Base kamoku: 3 KYU.', true, true, 1, 'LEGACY EXAMENES'),
  ('3 KYU', 'Mae ukemi', 'ukemi', 'Copiado del examen progresivo infantil antiguo. Bloque original: Ukemi. Base kamoku: 3 KYU.', true, true, 2, 'LEGACY EXAMENES'),
  ('3 KYU', 'Tenchi ken dai ni', 'kata_tanen', 'Copiado del examen progresivo infantil antiguo. Bloque original: Kata tan-en. Base kamoku: 3 KYU.', true, true, 3, 'LEGACY EXAMENES'),
  ('3 KYU', 'Sango', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 3 KYU.', true, true, 4, 'LEGACY EXAMENES'),
  ('3 KYU', 'Yongo', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 3 KYU.', true, true, 5, 'LEGACY EXAMENES'),
  ('3 KYU', 'Tenchu', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 3 KYU.', true, true, 6, 'LEGACY EXAMENES'),
  ('3 KYU', 'Amon', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 3 KYU.', true, true, 7, 'LEGACY EXAMENES'),
  ('3 KYU', 'Soto uke zuki (ura) renhanko', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 3 KYU.', true, true, 8, 'LEGACY EXAMENES'),
  ('3 KYU', 'Katate okuri gote', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 3 KYU.', true, true, 9, 'LEGACY EXAMENES'),
  ('3 KYU', 'Soto uke zuki (omote) renhanko', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 3 KYU.', true, true, 10, 'LEGACY EXAMENES'),
  ('3 KYU', 'Okuri maki tembin', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 3 KYU.', true, true, 11, 'LEGACY EXAMENES'),
  ('3 KYU', 'Tsubame gaeshi renhanko', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 3 KYU.', true, true, 12, 'LEGACY EXAMENES'),
  ('3 KYU', 'Kiri nuki (uchi)', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 3 KYU.', true, true, 13, 'LEGACY EXAMENES'),
  ('3 KYU', 'Ushiro ryusui geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 3 KYU.', true, true, 14, 'LEGACY EXAMENES'),
  ('3 KYU', 'Kiri nuki (soto)', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 3 KYU.', true, true, 15, 'LEGACY EXAMENES'),
  ('3 KYU', 'Shita uke jun geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 3 KYU.', true, true, 16, 'LEGACY EXAMENES'),
  ('3 KYU', 'Tsuki nuki (soto)', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 3 KYU.', true, true, 17, 'LEGACY EXAMENES'),
  ('3 KYU', 'Uchi uke geri (ura)', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 3 KYU.', true, true, 18, 'LEGACY EXAMENES'),
  ('3 KYU', 'Tsuki nuki (uchi)', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 3 KYU.', true, true, 19, 'LEGACY EXAMENES'),
  ('3 KYU', 'Uchi uke geri (omote)', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 3 KYU.', true, true, 20, 'LEGACY EXAMENES'),
  ('3 KYU', 'Ryote tsuki nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 3 KYU.', true, true, 21, 'LEGACY EXAMENES'),
  ('3 KYU', 'Katate Juji nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 3 KYU.', true, true, 22, 'LEGACY EXAMENES'),
  ('3 KYU', 'Ryote Juji nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 3 KYU.', true, true, 23, 'LEGACY EXAMENES'),
  ('3 KYU', 'Gentei goho (combination attacks)', 'randori', 'Copiado del examen progresivo infantil antiguo. Bloque original: Randori. Base kamoku: 3 KYU.', true, true, 24, 'LEGACY EXAMENES'),
  ('3 KYU', 'Gentei juho (grabs with strikes)', 'randori', 'Copiado del examen progresivo infantil antiguo. Bloque original: Randori. Base kamoku: 3 KYU.', true, true, 25, 'LEGACY EXAMENES'),
  ('3 KYU', 'Doshin So y la fundación del Shorinji Kempo', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 3 KYU.', true, true, 26, 'LEGACY EXAMENES'),
  ('3 KYU', 'Sobre Chinkon', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 3 KYU.', true, true, 27, 'LEGACY EXAMENES'),
  ('3 KYU', 'El Dokun', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 3 KYU.', true, true, 28, 'LEGACY EXAMENES'),
  ('3 KYU', 'Qué es el Budo y por qué lo practicamos', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 3 KYU.', true, true, 29, 'LEGACY EXAMENES'),
  ('3 KYU', 'Gyo: la disciplina del Shorinji Kempo', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 3 KYU.', true, true, 30, 'LEGACY EXAMENES'),
  ('3 KYU', 'Mitad para tu propia felicidad, mitad para la de los demás', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 3 KYU.', true, true, 31, 'LEGACY EXAMENES'),
  ('3 KYU', 'Kumi embu list 2: select option A or B and perform with a partner, following taikai rules', 'embu', 'Copiado del examen progresivo infantil antiguo. Bloque original: Embu. Base kamoku: 3 KYU.', true, true, 32, 'LEGACY EXAMENES'),
  ('2 KYU', 'Midare gamae', 'tai_gamae', 'Copiado del examen progresivo infantil antiguo. Bloque original: Tai gamae. Base kamoku: 2 KYU.', true, true, 1, 'LEGACY EXAMENES'),
  ('2 KYU', 'Tobi komi mae ukemi (to clear obstacle)', 'ukemi', 'Copiado del examen progresivo infantil antiguo. Bloque original: Ukemi. Base kamoku: 2 KYU.', true, true, 2, 'LEGACY EXAMENES'),
  ('2 KYU', 'Tenchi ken dai san & yon', 'kata_tanen', 'Copiado del examen progresivo infantil antiguo. Bloque original: Kata tan-en. Base kamoku: 2 KYU.', true, true, 3, 'LEGACY EXAMENES'),
  ('2 KYU', 'Giwa ken dai ni', 'kata_tanen', 'Copiado del examen progresivo infantil antiguo. Bloque original: Kata tan-en. Base kamoku: 2 KYU.', true, true, 4, 'LEGACY EXAMENES'),
  ('2 KYU', 'Giwa ken dai ichi', 'kata_sotai', 'Copiado del examen progresivo infantil antiguo. Bloque original: Kata sotai. Base kamoku: 2 KYU.', true, true, 5, 'LEGACY EXAMENES'),
  ('2 KYU', 'Sunmyaku', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 2 KYU.', true, true, 6, 'LEGACY EXAMENES'),
  ('2 KYU', 'San inko', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 2 KYU.', true, true, 7, 'LEGACY EXAMENES'),
  ('2 KYU', 'Fushi', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 2 KYU.', true, true, 8, 'LEGACY EXAMENES'),
  ('2 KYU', 'Ura Uchi age zuki', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 2 KYU.', true, true, 9, 'LEGACY EXAMENES'),
  ('2 KYU', 'Omote Uchi age zuki', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 2 KYU.', true, true, 10, 'LEGACY EXAMENES'),
  ('2 KYU', 'Ude juji, tate gassho gatame', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 2 KYU.', true, true, 11, 'LEGACY EXAMENES'),
  ('2 KYU', 'Ura Uchi age geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 2 KYU.', true, true, 12, 'LEGACY EXAMENES'),
  ('2 KYU', 'Omote Uchi age geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 2 KYU.', true, true, 13, 'LEGACY EXAMENES'),
  ('2 KYU', 'Ryote maki nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 2 KYU.', true, true, 14, 'LEGACY EXAMENES'),
  ('2 KYU', 'Ura Soto uke geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 2 KYU.', true, true, 15, 'LEGACY EXAMENES'),
  ('2 KYU', 'Omote Soto uke geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 2 KYU.', true, true, 16, 'LEGACY EXAMENES'),
  ('2 KYU', 'Ryote okuri gote, ura gatame', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 2 KYU.', true, true, 17, 'LEGACY EXAMENES'),
  ('2 KYU', 'Soto oshi uke zuki', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 2 KYU.', true, true, 18, 'LEGACY EXAMENES'),
  ('2 KYU', 'Johaku maki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 2 KYU.', true, true, 19, 'LEGACY EXAMENES'),
  ('2 KYU', 'Uchi oshi uke zuki', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 2 KYU.', true, true, 20, 'LEGACY EXAMENES'),
  ('2 KYU', 'Katate Juji gote', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 2 KYU.', true, true, 21, 'LEGACY EXAMENES'),
  ('2 KYU', 'Ryote Juji gote', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 2 KYU.', true, true, 22, 'LEGACY EXAMENES'),
  ('2 KYU', 'Chidori gaeshi kari ashi', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 2 KYU.', true, true, 23, 'LEGACY EXAMENES'),
  ('2 KYU', 'Nidan nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 2 KYU.', true, true, 24, 'LEGACY EXAMENES'),
  ('2 KYU', 'Kinteki (gyaku) geri hiza uke nami gaeshi', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 2 KYU.', true, true, 25, 'LEGACY EXAMENES'),
  ('2 KYU', 'Morote tsuki nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 2 KYU.', true, true, 26, 'LEGACY EXAMENES'),
  ('2 KYU', 'Gassho nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 2 KYU.', true, true, 27, 'LEGACY EXAMENES'),
  ('2 KYU', 'Gyaku gote ura gaeshi nage', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 2 KYU.', true, true, 28, 'LEGACY EXAMENES'),
  ('2 KYU', 'Goho free randori', 'randori', 'Copiado del examen progresivo infantil antiguo. Bloque original: Randori. Base kamoku: 2 KYU.', true, true, 29, 'LEGACY EXAMENES'),
  ('2 KYU', 'Gentei juho randori', 'randori', 'Copiado del examen progresivo infantil antiguo. Bloque original: Randori. Base kamoku: 2 KYU.', true, true, 30, 'LEGACY EXAMENES'),
  ('2 KYU', 'Establécete a ti mismo y vive en armonía con los demás', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 2 KYU.', true, true, 31, 'LEGACY EXAMENES'),
  ('2 KYU', 'Ken Zen Ichi Nyo', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 2 KYU.', true, true, 32, 'LEGACY EXAMENES'),
  ('2 KYU', 'Riki Ai Funi', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 2 KYU.', true, true, 33, 'LEGACY EXAMENES'),
  ('2 KYU', 'Pautas para un entrenamiento eficaz', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 2 KYU.', true, true, 34, 'LEGACY EXAMENES'),
  ('2 KYU', 'La mentalidad de crecimiento', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 2 KYU.', true, true, 35, 'LEGACY EXAMENES'),
  ('2 KYU', 'Ars Longa, Vita Brevis', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 2 KYU.', true, true, 36, 'LEGACY EXAMENES'),
  ('2 KYU', 'Kumi embu list 3: construct an embu using any six listed sequences, following taikai rules', 'embu', 'Copiado del examen progresivo infantil antiguo. Bloque original: Embu. Base kamoku: 2 KYU.', true, true, 37, 'LEGACY EXAMENES'),
  ('1 KYU', 'Tate muso gamae', 'tai_gamae', 'Copiado del examen progresivo infantil antiguo. Bloque original: Tai gamae. Base kamoku: 1 KYU.', true, true, 1, 'LEGACY EXAMENES'),
  ('1 KYU', 'Yoko muso gamae', 'tai_gamae', 'Copiado del examen progresivo infantil antiguo. Bloque original: Tai gamae. Base kamoku: 1 KYU.', true, true, 2, 'LEGACY EXAMENES'),
  ('1 KYU', 'Tobi ukemi from nage waza (gyaku gote)', 'ukemi', 'Copiado del examen progresivo infantil antiguo. Bloque original: Ukemi. Base kamoku: 1 KYU.', true, true, 3, 'LEGACY EXAMENES'),
  ('1 KYU', 'Tenchi ken dai ni', 'kata_sotai', 'Copiado del examen progresivo infantil antiguo. Bloque original: Kata sotai. Base kamoku: 1 KYU.', true, true, 4, 'LEGACY EXAMENES'),
  ('1 KYU', 'Kekkai', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 1 KYU.', true, true, 5, 'LEGACY EXAMENES'),
  ('1 KYU', 'Matsukaze', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 1 KYU.', true, true, 6, 'LEGACY EXAMENES'),
  ('1 KYU', 'Rinkyu', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 1 KYU.', true, true, 7, 'LEGACY EXAMENES'),
  ('1 KYU', 'Danchu', 'keimyaku', 'Copiado del examen progresivo infantil antiguo. Bloque original: Keimyaku. Base kamoku: 1 KYU.', true, true, 8, 'LEGACY EXAMENES'),
  ('1 KYU', 'Kusshin zuki', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 1 KYU.', true, true, 9, 'LEGACY EXAMENES'),
  ('1 KYU', 'Oshi kiri nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 10, 'LEGACY EXAMENES'),
  ('1 KYU', 'Kusshin geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 1 KYU.', true, true, 11, 'LEGACY EXAMENES'),
  ('1 KYU', 'Kiri kaeshi nuki (katate)', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 12, 'LEGACY EXAMENES'),
  ('1 KYU', 'Kusshin zuki geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 1 KYU.', true, true, 13, 'LEGACY EXAMENES'),
  ('1 KYU', 'Kiri kaeshi nuki (morote)', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 14, 'LEGACY EXAMENES'),
  ('1 KYU', 'Han tenshin geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 1 KYU.', true, true, 15, 'LEGACY EXAMENES'),
  ('1 KYU', 'Katate Kiri gote', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 16, 'LEGACY EXAMENES'),
  ('1 KYU', 'Morote Kiri gote', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 17, 'LEGACY EXAMENES'),
  ('1 KYU', 'Yoko tenshin geri', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 1 KYU.', true, true, 18, 'LEGACY EXAMENES'),
  ('1 KYU', 'Sankaku nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 19, 'LEGACY EXAMENES'),
  ('1 KYU', 'Uchi uke zuki (omote)', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 1 KYU.', true, true, 20, 'LEGACY EXAMENES'),
  ('1 KYU', 'Sode dori', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 21, 'LEGACY EXAMENES'),
  ('1 KYU', 'Furi ten ni', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 1 KYU.', true, true, 22, 'LEGACY EXAMENES'),
  ('1 KYU', 'Sode maki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 23, 'LEGACY EXAMENES'),
  ('1 KYU', 'Tsuki ten ni', 'goho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Goho. Base kamoku: 1 KYU.', true, true, 24, 'LEGACY EXAMENES'),
  ('1 KYU', 'Sode maki tembin', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 25, 'LEGACY EXAMENES'),
  ('1 KYU', 'Eri nuki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 26, 'LEGACY EXAMENES'),
  ('1 KYU', 'Ude maki', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 27, 'LEGACY EXAMENES'),
  ('1 KYU', 'Eri juji', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 28, 'LEGACY EXAMENES'),
  ('1 KYU', 'Kata muna otoshi', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 29, 'LEGACY EXAMENES'),
  ('1 KYU', 'Ryaku juji gote', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 30, 'LEGACY EXAMENES'),
  ('1 KYU', 'Maki juji gote', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 31, 'LEGACY EXAMENES'),
  ('1 KYU', 'Katate Oshi gote', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 32, 'LEGACY EXAMENES'),
  ('1 KYU', 'Ryote Oshi gote', 'juho', 'Copiado del examen progresivo infantil antiguo. Bloque original: Juho. Base kamoku: 1 KYU.', true, true, 33, 'LEGACY EXAMENES'),
  ('1 KYU', 'Goho free randori', 'randori', 'Copiado del examen progresivo infantil antiguo. Bloque original: Randori. Base kamoku: 1 KYU.', true, true, 34, 'LEGACY EXAMENES'),
  ('1 KYU', 'Gentei juho randori', 'randori', 'Copiado del examen progresivo infantil antiguo. Bloque original: Randori. Base kamoku: 1 KYU.', true, true, 35, 'LEGACY EXAMENES'),
  ('1 KYU', 'Shushu Koju', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 1 KYU.', true, true, 36, 'LEGACY EXAMENES'),
  ('1 KYU', 'Fusatsu Katsujin', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 1 KYU.', true, true, 37, 'LEGACY EXAMENES'),
  ('1 KYU', 'Go Ju Ittai', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 1 KYU.', true, true, 38, 'LEGACY EXAMENES'),
  ('1 KYU', 'Kumite Shutai', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 1 KYU.', true, true, 39, 'LEGACY EXAMENES'),
  ('1 KYU', 'Fuhai Shoju', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 1 KYU.', true, true, 40, 'LEGACY EXAMENES'),
  ('1 KYU', 'Los tres niveles de dominio de un arte (Gi, Jutsu, Ryaku)', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 1 KYU.', true, true, 41, 'LEGACY EXAMENES'),
  ('1 KYU', 'Las tres etapas del aprendizaje de una habilidad (Shu, Ha, Ri)', 'gakka', 'Copiado del examen progresivo infantil antiguo. Bloque original: Gakka. Base kamoku: 1 KYU.', true, true, 42, 'LEGACY EXAMENES'),
  ('1 KYU', 'Kumi embu list 4: construct a six-sequence embu using techniques from the list and perform with a partner, following taikai rules', 'embu', 'Copiado del examen progresivo infantil antiguo. Bloque original: Embu. Base kamoku: 1 KYU.', true, true, 43, 'LEGACY EXAMENES')
on conflict do nothing;
