-- Refresh adult technique summaries from the BSKF kyu/dan syllabus extracts.
-- The system keeps split SKBC technique rows by ID_TECNICA and applies the matching syllabus summary.

with summaries(legacy_id, summary_es) as (
  values
  ('TEC001', 'Posicion: tai gamae. Atacante: jodan gyaku zuki Defensor: uchi uke, chudan gyaku zuki a suigetsu'),
  ('TEC002', 'Posicion: tai gamae. Atacante: jodan gyaku zuki Defensor: kani ashi, gyaku geri'),
  ('TEC003', 'Posicion: tai gamae. Atacante: gyaku shuto uchi Defensor: gyaku uwa uke, chudan jun zuki'),
  ('TEC004', 'Posicion: tai gamae. & Hiraki Atacante: gyaku shuto uchi Defensor: jun uwa uke, jun geri'),
  ('TEC005', 'Posicion: hiraki gamae. Atacante: agarre del mismo lado por fuera de la muñeca Defensor: kumade zuki a mikazuki'),
  ('TEC006', 'Posicion: hiraki gamae. Atacante: agarre cruzado por dentro de la muñeca Defensor: uraken uchi a sango/yongo'),
  ('TEC007', 'Posicion: hiraki gamae. Atacante: agarre cruzado por dentro de la muñeca Defensor: atacar dai kento'),
  ('TEC008', 'Posicion: tai gamae. Shikake waza Atacante: atacar hakusetsu, luxacion de brazo de pie, conduccion'),
  ('TEC009', 'Posicion: tai gamae. Atacante: gyaku shuto uchi Defensor: nio gamae; mae ryusui uke, gyaku geri'),
  ('TEC010', 'Posicion: tai gamae. Atacante: chudan gyaku zuki Defensor: hasso gamae; jun shita uke, gyaku geri'),
  ('TEC011', 'Posicion: hiraki gamae. Atacante: jo chu ni ren zuki Defensor: ni ren uke, jun geri'),
  ('TEC012', 'Posicion: tai gamae. Atacante: jun mawashi geri Defensor: juji uke, jun o mawashi geri'),
  ('TEC013', 'Posicion: tai gamae. Defensor: sashi kae ashi uwa uke, chudan jun zuki, kumade zuki, mas keri ten ichi ren han ko'),
  ('TEC014', 'Posicion: hiraki gamae. Como en yori nuki Atacante: gira la mano hacia fuera para resistir yori nuki'),
  ('TEC015', 'Posicion: tai gamae. Atacante: agarra ambas muñecas Defensor: me uchi chudan dan zuki'),
  ('TEC016', 'Posicion: tai gamae. Atacante: agarra uno o ambos brazos por el biceps y empuja Defensor: gyaku gedan gamae'),
  ('TEC5030', 'Posicion: tai gamae. Atacante: agarra uno o ambos brazos por el biceps y empuja Defensor: gyaku gedan gamae'),
  ('TEC017', 'Posicion: tai gamae. Atacante: Como en johaku nuki Defensor: gyaku gedan gamae; ryote: mano adelantada nuki primero'),
  ('TEC5031', 'Posicion: tai gamae. Atacante: agarra uno o ambos brazos por el biceps y empuja Defensor: gyaku gedan gamae'),
  ('TEC018', 'Posicion: tai gamae. Atacante: agarra una o ambas mangas altas y tira Defensor: gyaku gedan gamae'),
  ('TEC5032', 'Posicion: tai gamae. Atacante: Como en johaku nuki Defensor: gyaku gedan gamae; ryote: mano adelantada nuki primero'),
  ('TEC5033', 'Posicion: tai gamae. Atacante: Como en johaku nuki Defensor: gyaku gedan gamae; ryote: mano adelantada nuki primero'),
  ('TEC5034', 'Posicion: tai gamae. Atacante: agarra una o ambas mangas altas y tira Defensor: gyaku gedan gamae'),
  ('TEC5035', 'Posicion: tai gamae. Atacante: agarra una o ambas mangas altas y tira Defensor: gyaku gedan gamae'),
  ('TEC019', 'Posicion: tai gamae. Atacante: jodan gyaku zuki. Defensor: gyaku soto uke, jun zuki; renhanko Como en uwa uke zuki (ura)'),
  ('TEC020', 'Posicion: hiraki gamae. Atacante: jodan gyaku zuki Defensor: ren han ko Como en uwa uke zuki (omote)'),
  ('TEC021', 'Posicion: hiraki gamae. Atacante: jodan gyaku zuki Defensor: taiki gamae; renhanko'),
  ('TEC022', 'Posicion: tai gamae. Atacante: jodan gyaku zuki Defensor: nio gamae; ryusui uke a rear, jun geri, juji ashi'),
  ('TEC023', 'Posicion: tai gamae. Atacante: chudan jun zuki Defensor: hasso gamae, gyaku shita uke, jun geri'),
  ('TEC024', 'Posicion: tai gamae. Atacante: jodan gyaku zuki Defensor: jun uchi uke, jun sokuto geri'),
  ('TEC025', 'Posicion: hiraki gamae. Atacante: jodan gyaku zuki Defensor: jun uchi uke, jun sokuto geri'),
  ('TEC026', 'Posicion: hiraki gamae. Como en maki nuki Defensor: yubi dori renko'),
  ('TEC027', 'Posicion: hiraki gamae. Como en okuri gote Atacante: gira hacia fuera a escapar de okuri gote'),
  ('TEC028', 'Posicion: tai gamae. Ofrece levantada mano adelantada Atacante: agarra por dentro de la muneca, tira'),
  ('TEC029', 'Posicion: hiraki gamae. Ofrece levantada mano adelantada Atacante: agarra por fuera de la muneca, tira'),
  ('TEC030', 'Posicion: hiraki gamae. Como en yori nuki. Atacante: empuja hacia abajo Defensor: tsuitate shuho, kinteki uchi'),
  ('TEC031', 'Posicion: hiraki gamae. Como en kote nuki. Atacante: empuja hacia abajo Defensor: tsuitate shuho, kinteki uchi'),
  ('TEC032', 'Posicion: tai gamae. Como en ryote yori nuki Defensor: tsuitate shuho, kinteki uchi, hiji ate'),
  ('TEC033', 'Posicion: hiraki gamae. ofrece la mano levantada(s) Atacante: mano adelantada(s) agarra por fuera de la muneca(s)'),
  ('TEC5036', 'Posicion: tai gamae. ofrece la mano levantada Atacante: ambas manos agarra la muñeca & empuja'),
  ('TEC5037', 'Posicion: tai gamae. ofrece la mano levantada Atacante: ambas manos agarra la muñeca & empuja'),
  ('TEC034', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan gyaku zuki'),
  ('TEC5038', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan gyaku zuki'),
  ('TEC035', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan jun zuki Defensor: jun uchi age, jun geri'),
  ('TEC5039', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan gyaku zuki'),
  ('TEC036', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan gyaku zuki Defensor: gyaku soto uke'),
  ('TEC5040', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan jun zuki Defensor: jun uchi age, jun geri'),
  ('TEC037', 'Posicion: tai gamae. Atacante: gyaku furi zuki Defensor: sashi kae ashi soto oshi uke; kumade zuki'),
  ('TEC5041', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan jun zuki Defensor: jun uchi age, jun geri'),
  ('TEC038', 'Posicion: hiraki gamae. Atacante: gyaku furi zuki'),
  ('TEC5042', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan gyaku zuki Defensor: gyaku soto uke'),
  ('TEC039', 'Posicion: tai gamae. Atacante: sashi kae ashi jodan jun zuki'),
  ('TEC5043', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Atacante: jodan gyaku zuki Defensor: gyaku soto uke'),
  ('TEC040', 'Posicion: tai gamae. Atacante: jun kinteki geri. Tambien desde hiraki (gyaku geri)'),
  ('TEC041', 'Posicion: tai gamae. Shikake waza Atacante: luxacion de brazo de pie, proyeccion y control, fumi geri'),
  ('TEC042', 'Posicion: tai gamae. Como en ryote yori nuki Defensor: segunda salida yori nuki'),
  ('TEC043', 'Posicion: tai gamae. Defensor: despues primero nuki, me uchi, directo a okuri gote, ura gatame'),
  ('TEC044', 'Posicion: tai gamae. Atacante: agarra el biceps Desde lado, y empuja Defensor: gyaku gedan gamae'),
  ('TEC045', 'Posicion: hiraki gamae. Atacante: Como en juji nuki Defensor: ryote (tai) no libera primero'),
  ('TEC5044', 'Posicion: hiraki gamae. Como en sei juji gote, pero ofrece la mano baja'),
  ('TEC046', 'Posicion: tai gamae. Como en ryote yori nuki Atacante: gira ambas manos inwards'),
  ('TEC5045', 'Posicion: hiraki gamae. Como en sei juji gote, pero ofrece la mano baja'),
  ('TEC047', 'Posicion: tai gamae. Atacante: dos manos agarra un brazo, empuja hacia abajo Defensor: kinteki uchi, hiji ate'),
  ('TEC048', 'Posicion: tai gamae. Como en kiri nuki Atacante: agarra ambas manos y tira'),
  ('TEC049', 'Posicion: hiraki gamae. Como en gyaku gote Defensor: proyeccion y control ura gatame'),
  ('TEC050', 'Posicion: tai gamae. Atacante: furi zuki Defensor: kusshin, jun uchi age uke, gyaku zuki'),
  ('TEC051', 'Posicion: tai gamae. Como en kusshin zuki, pero distancia mas amplia Defensor: gyaku geri'),
  ('TEC052', 'Posicion: tai gamae. Defensor: chudan gyaku zuki followed by gyaku (mawashi) geri'),
  ('TEC053', 'Posicion: hiraki gamae. Atacante: ichiji gamae; gyaku geri Defensor: chudan gamae; uchi otoshi uke, jun geri'),
  ('TEC054', 'Posicion: tai gamae. Atacante: ichiji gamae; gyaku geri Defensor: chudan gamae; jun uchi harai uke, jun geri'),
  ('TEC055', 'Posicion: hiraki gamae. Atacante: jodan gyaku zuki Defensor: jun uchi uke, chudan gyaku zuki'),
  ('TEC056', 'Posicion: hiraki gamae. Atacante: jodan jun furi zuki, chudan gyaku furi zuki Defensor: sokuto geri'),
  ('TEC057', 'Posicion: hiraki gamae. Atacante: jo jo ni ren zuki Defensor: jun uchi age uchi otoshi dan uke, jun geri'),
  ('TEC058', 'Posicion: tai gamae. Como en ryote johaku nuki'),
  ('TEC059', 'Posicion: hiraki gamae. Atacante: agarra la parte superior de la muneca, tira & golpea / gira'),
  ('TEC060', 'Posicion: hiraki gamae. Atacante: ambas manos agarra la muñeca para detencion / proyeccion'),
  ('TEC061', 'Posicion: hiraki gamae. Como en kiri kaeshi nuki (morote) Defensor: gyaku gedan gamae'),
  ('TEC5046', 'Posicion: hiraki gamae. Como en kiri kaeshi nuki (morote) Defensor: gyaku gedan gamae'),
  ('TEC062', 'Posicion: hiraki gamae. Atacante: ''hammer'' proyeccion o detencion Defensor: gyaku gedan gamae, sankaku shuho'),
  ('TEC5047', 'Posicion: hiraki gamae. Como en kiri kaeshi nuki (morote) Defensor: gyaku gedan gamae'),
  ('TEC063', 'Posicion: tai gamae. Como en sode nuki. Atacante: agarra alta manga & tira'),
  ('TEC064', 'Posicion: tai gamae. Como en sode nuki. Atacante: agarra atras de alta manga Defensor: gyaku gedan gamae'),
  ('TEC065', 'Posicion: tai gamae. Como en sode maki. Atacante: gira hacia fuera a escapar de sode maki'),
  ('TEC066', 'Posicion: tai gamae. Atacante: agarra la solapa baja o la chaqueta Defensor: gyaku gedan gamae'),
  ('TEC067', 'Posicion: tai gamae. Como en eri nuki. Atacante: agarra la solapa baja o la chaqueta'),
  ('TEC068', 'Posicion: hiraki gamae. Atacante: agarra la solapa alta, puno horizontal Defensor: golpea hacia arriba con nai wanto'),
  ('TEC069', 'Posicion: hiraki gamae. Atacante: agarra la solapa alta, puno vertical'),
  ('TEC070', 'Posicion: hiraki gamae. Como en sei juji gote, pero ofrece la mano baja'),
  ('TEC071', 'Posicion: hiraki gamae. Como en sei juji gote o ryaku juji gote'),
  ('TEC072', 'Posicion: hiraki gamae. Como en yori nuki. Atacante: gira hacia dentro a impedir yori nuki Defensor: kannuki gatame'),
  ('TEC5048', 'Posicion: tai gamae. Atacante: agarra ambas muñecas, gira hacia dentro. Defensor: nuki primero'),
  ('TEC5049', 'Posicion: tai gamae. Atacante: agarra ambas muñecas, gira hacia dentro. Defensor: nuki primero'),
  ('TEC073', 'Posicion: hiraki gamae. Atacante: jun mawashi geri Defensor: nio gamae; kokutsu dachi, gyaku geri'),
  ('TEC074', 'Posicion: hiraki gamae. Atacante: jun mawashi geri Defensor: zenkutsu dachi, jun geri'),
  ('TEC075', 'Posicion: hiraki gamae. Atacante: sashi kae ashi chudan jun zuki Defensor: hasso gamae'),
  ('TEC076', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote) Defensor: hasso gamae, shita uke, jodan gyaku zuki'),
  ('TEC5050', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote) Defensor: hasso gamae, shita uke, jodan gyaku zuki'),
  ('TEC077', 'Posicion: hiraki gamae. Atacante: jo chu ni ren zuki gyaku mawashi geri'),
  ('TEC5051', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote) Defensor: hasso gamae, shita uke, jodan gyaku zuki'),
  ('TEC078', 'Posicion: tai gamae. Defensor: gyaku uchi uke, jun shita uke, girar para juji uke geri'),
  ('TEC079', 'Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku zuki o jun zuki (tai o hiraki) Defensor: midare g., gyaku hangetsu kakete uke, jun zuki'),
  ('TEC080', 'Posicion: hiraki gamae. Atacante: jo chu jo san ren zuki'),
  ('TEC5052', 'Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku zuki o jun zuki (tai o hiraki) Defensor: midare g., gyaku hangetsu kakete uke, jun zuki'),
  ('TEC081', 'Posicion: tai gamae. Defensor: gyaku uchi uke, jun shita uke, gyaku uwa uke zuki'),
  ('TEC5053', 'Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku zuki o jun zuki (tai o hiraki) Defensor: midare g., gyaku hangetsu kakete uke, jun zuki'),
  ('TEC082', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote) Atacante: gyaku furi zuki Defensor: tate muso; jun o sokuto geri kaeshi'),
  ('TEC083', 'Posicion: tai gamae. Atacante: jodan gyaku furi zuki'),
  ('TEC084', 'Posicion: tai gamae. Atacante: jun mawashi geri a gedan, chudan o jodan'),
  ('TEC5054', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote) Atacante: gyaku furi zuki Defensor: tate muso; jun o sokuto geri kaeshi'),
  ('TEC5055', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote) Atacante: gyaku furi zuki Defensor: tate muso; jun o sokuto geri kaeshi'),
  ('TEC085', 'Posicion: cualquier kamae indicado. cualquier agarre de muneca por dentro o por fuera, golpea a libera'),
  ('TEC5056', 'Posicion: cualquier kamae indicado. cualquier agarre de muneca por dentro o por fuera, golpea a libera'),
  ('TEC086', 'Posicion: tai gamae. Shikake waza. Atacante: dos manos agarra para luxacion de codo'),
  ('TEC5057', 'Posicion: cualquier kamae indicado. cualquier agarre de muneca por dentro o por fuera, golpea a libera'),
  ('TEC087', 'Posicion: tai gamae. Defensor: manji gamae; defensa contra gyaku tembin'),
  ('TEC088', 'Posicion: tai gamae. Como en johaku dori'),
  ('TEC089', 'Posicion: tai gamae. Atacante: intento de ude gyaku dori (maki tembin), both'),
  ('TEC090', 'Posicion: tai gamae. Como en kiri nuki (uchi)'),
  ('TEC091', 'Posicion: tai gamae. Atacante: intento de ude gyaku dori (maki tembin) Defensor: ura gatame'),
  ('TEC092', 'Posicion: tai gamae. ofrece la mano levantada Atacante: ambas manos agarra la muñeca & empuja'),
  ('TEC093', 'Posicion: tai gamae. ofrece la mano levantada Atacante: ambas manos agarra la muñeca & empuja'),
  ('TEC094', 'Posicion: tai gamae. Como en shita uke geri'),
  ('TEC095', 'Posicion: hiraki gamae. Atacante: empuja alejando directo a resistir kiri gote Defensor: gyaku gedan gamae'),
  ('TEC096', 'Posicion: hiraki gamae. Atacante: empuja despues gira hacia fuera a resistir kiri gote Defensor: gyaku gedan gamae'),
  ('TEC5058', 'Posicion: hiraki gamae. Atacante: empuja alejando directo a resistir kiri gote Defensor: gyaku gedan gamae'),
  ('TEC097', 'Posicion: tai gamae. Atacante: agarra la parte inferior de la muneca Defensor: gyaku gedan gamae'),
  ('TEC5059', 'Posicion: hiraki gamae. Atacante: empuja alejando directo a resistir kiri gote Defensor: gyaku gedan gamae'),
  ('TEC098', 'Posicion: tai gamae. Como en katate oshi nuki Defensor: gyaku gedan gamae; atacar sunmyaku, kannuki gatame'),
  ('TEC1001', 'Posicion: tai gamae. Atacante: jo chu. Defensor: gyaku uwa uke, jun shita uke'),
  ('TEC1002', 'Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku, chudan jun zuki Defensor: hiraki (ura), uchi uke, harai uke, geri; tai (omote), hiraki sagari con uchi uke'),
  ('TEC_005060', 'Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku, chudan jun zuki Defensor: hiraki (ura), uchi uke, harai uke, geri; tai (omote), hiraki sagari con uchi uke'),
  ('TEC1003', 'Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku, chudan jun zuki Defensor: hiraki (ura), uchi uke, harai uke, geri; tai (omote), hiraki sagari con uchi uke'),
  ('TEC_005061', 'Posicion: tai/hiraki segun ura u omote. Atacante: jodan gyaku, chudan jun zuki Defensor: hiraki (ura), uchi uke, harai uke, geri; tai (omote), hiraki sagari con uchi uke'),
  ('TEC1004', 'Posicion: hiraki gamae. Atacante: jun furi zuki, chudan gyaku choku zuki'),
  ('TEC1005', 'Posicion: tai gamae. Atacante: hebite zuki jun kinteki geri. Defensor: yoko muso; ken uke a taisho'),
  ('TEC1006', 'Posicion: hiraki gamae. Atacante: toride zuki gyaku kinteki geri. Defensor: Como en jun'),
  ('TEC1007', 'Posicion: hiraki gamae. Atacante: jun mawashi, gyaku zuki. Defensor: kesshu'),
  ('TEC1008', 'Posicion: hiraki gamae. Atacante: jun sokuto, jo chu ni ren zuki'),
  ('TEC1009', 'Posicion: tai gamae. Atacante: gyaku kinteki, jun shuto giri chudan zuki'),
  ('TEC1010', 'Posicion: tai gamae. Atacante: gyaku zuki. Defensor: midare; hangetsu kakete uke'),
  ('TEC_005062', 'Posicion: tai gamae. Atacante: jo chu mawashi. Defensor: soto uke, girar, hasami uke'),
  ('TEC_005063', 'Posicion: tai gamae. Atacante: cuchillada descendente desde arriba. Defensor: aiki; mae ryusui geri'),
  ('TEC_005064', 'Posicion: tai gamae. Atacante: cuchillada chudan. Defensor: hasso; golpea la muñeca (yokei) uchi otoshi'),
  ('TEC_005065', 'Posicion: tai gamae. Atacante: cuchillada chudan. Defensor: hasso gamae'),
  ('TEC1011', 'Posicion: tai gamae. Atacante: retrocede tirando despues de ura ken. Defensor: gyakute gatame'),
  ('TEC_005066', 'Posicion: hiraki gamae. Adaptacion de gyaku gote. Atacante: entra cerrando distancia kagite'),
  ('TEC1012', 'Posicion: hiraki gamae. Adaptacion de gyaku gote. Atacante: entra cerrando distancia kagite'),
  ('TEC_005067', 'Posicion: hiraki gamae. Adaptacion de gyaku gote. Atacante: extendido kagite'),
  ('TEC1013', 'Posicion: hiraki gamae. Adaptacion de gyaku gote. Atacante: extendido kagite'),
  ('TEC1015', 'Posicion: hiraki gamae. Adaptacion de gyaku gote. Atacante: empuja alejando'),
  ('TEC1016', 'Posicion: tai gamae. Atacante: ura ken uchi. Defensor: kakete uke; kannuki gatame'),
  ('TEC1017', 'Posicion: tai gamae. Atacante: retrocede tirando despues de ura ken. Defensor: gyakute gatame'),
  ('TEC1018', 'Posicion: tai gamae. Atacante: shikake waza; golpea gori'),
  ('TEC1019', 'Posicion: cualquier kamae indicado. Como en gyaku gote. Atacante: empuja alejando'),
  ('TEC1020', 'Posicion: tai gamae. Desde saludo de manos'),
  ('TEC_005068', 'Posicion: hiraki gamae. Atacante: intento de se nage. Defensor: jun mawashi atemi'),
  ('TEC_005069', 'Posicion: hiraki gamae. Atacante: intento de se nage, codos hacia fuera'),
  ('TEC_005070', 'Posicion: hiraki gamae. Como en wa nuki. Defensor: tate ichiji gatame, sekoshi ichiji gatame (con uchi uke geri), kumo garami'),
  ('TEC_005071', 'Posicion: hiraki gamae. Como en morote maki nuki. Defensor: tsuri age ura gatame, hiza gatame, baku ho ichi'),
  ('TEC_005072', 'Posicion: hiraki gamae. 1: shikake waza. 2: Desde okuri gote. atacar chuin.'),
  ('TEC_005073', 'Posicion: tai gamae. Atacante: shikake waza; pasa caminando & agarra la muñeca'),
  ('TEC_005074', 'Posicion: hiraki gamae. Atacante: levanta el codo a escapar de okuri gote'),
  ('TEC_005075', 'Posicion: tai gamae. Atacante: ryote dori, empuja una mano atras. Defensor: usa el cuello'),
  ('TEC_005076', 'Posicion: hiraki gamae. Como en maki tembin. Defensor: proyeccion away'),
  ('TEC_005077', 'Posicion: tai gamae. Atacante: shikake waza; agarra primero la muñeca'),
  ('TEC_005078', 'Posicion: tai gamae. Atacante: agarra la solapa. Defensor: aiki; usa una mano'),
  ('TEC_005079', 'Posicion: tai gamae. Atacante: agarra ambas solapas. Defensor: aiki; golpea sumyaku'),
  ('TEC_005080', 'Posicion: tai gamae. Atacante: agarra la solapa & tira, golpea. Defensor: gyaku gedan gamae'),
  ('TEC_005081', 'Posicion: tai gamae. Atacante: Como en maki otoshi, empuja. Defensor: gyaku gedan gamae'),
  ('TEC_005082', 'Posicion: tai gamae. Atacante: agarra ambas muñecas, gira hacia dentro. Defensor: nuki primero'),
  ('TEC_005083', 'Posicion: cualquier kamae indicado. dos atacantes, cada uno agarra un brazo y tira 2dan nd'),
  ('TEC3001', 'Posicion: cualquier kamae indicado. Atacante: cualquier golpe de puño. Defensor: yoko muso gamae; jun geri'),
  ('TEC3002', 'Posicion: tai gamae. Atacante: jun dan geri (kinteki, mawashi)'),
  ('TEC3003', 'Posicion: cualquier kamae indicado. Atacante: gedan jun sokuto geri (a fushi o rodilla)'),
  ('TEC3004', 'Posicion: tai gamae. Atacante: sashi kae jun zuki. Defensor: taiki; kari ashi'),
  ('TEC3005', 'Posicion: tai gamae. Atacante: gyaku zuki. Defensor: taiki; tenchu uchi, derribo al cuerpo'),
  ('TEC3006', 'Posicion: tai gamae. Atacante: jo chu. Defensor: midari; kumade, hiza geri, sukui kubi nage'),
  ('TEC3007', 'Posicion: hiraki gamae. Atacante: jun mawashi. Defensor: taiki (abierto); gyaku shita uke'),
  ('TEC3008', 'Posicion: hiraki gamae. Atacante: jun mawashi, gyaku zuki. Defensor: seiza; bloquea kori'),
  ('TEC3009', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Defensor: tate muso gamae; mano adelantada cover uchi uke'),
  ('TEC3010', 'Posicion: tai/hiraki segun ura u omote. Tai (ura), hiraki (omote). Defensor: mano adelantada cover uchi uke'),
  ('TEC3011', 'Posicion: tai gamae. Defensor: ura ken tsuki komi a jinchu o nichigetsu'),
  ('TEC3012', 'Posicion: hiraki gamae. Defensor: ura ken tsuki komi o ura ken uchi a sango'),
  ('TEC3013', 'Posicion: tai gamae. Defensor: Como en uwa uke zuki (omote)'),
  ('TEC3014', 'Posicion: hiraki gamae. Atacante: empuja a muslo o pecho. Defensor: seiza o de pie'),
  ('TEC3015', 'Posicion: hiraki gamae. Defensor: seiza; kuzushi, fukko; okuri yoko tembin, ura gatame'),
  ('TEC3016', 'Posicion: hiraki gamae. Defensor: seiza; kuzushi, fukko; osae yubi gatame'),
  ('TEC3017', 'Posicion: hiraki gamae. Defensor: seiza; kuzushi, fukko; kannuki gatame'),
  ('TEC3018', 'Posicion: tai gamae. Atacante: shikake waza'),
  ('TEC3019', 'Posicion: cualquier kamae indicado. Atacante: Como en gyaku gote'),
  ('TEC3020', 'Posicion: hiraki gamae. Atacante: Como en yori nuki'),
  ('TEC3021', 'Posicion: tai gamae. Atacante: saludo de manos'),
  ('TEC3022', 'Posicion: tai gamae. Atacante: ryote agarra'),
  ('TEC3023', 'Posicion: cualquier kamae indicado. Atacante: intento de ippon se nage o gyaku tembin'),
  ('TEC3024', 'Posicion: tai gamae. Atacante: agarra la manga, ashi barai. Defensor: aiki gamae'),
  ('TEC3025', 'Posicion: hiraki gamae. Atacante: agarra la manga bocamanga, dedos por dentro. Defensor: aiki'),
  ('TEC3026', 'Posicion: hiraki gamae. Atacante: agarra la manga bocamanga, pulgar por dentro. Defensor: aiki'),
  ('TEC3027', 'Posicion: hiraki gamae. Como en kiri gote. Atacante: suelta el agarre. Defensor: gyaku gedan'),
  ('TEC3028', 'Posicion: hiraki gamae. Como en kiri gote. Atacante: suelta el agarre. Defensor: gyaku gedan; ura gassho gatame'),
  ('TEC3029', 'Posicion: hiraki gamae. Atacante: intento de hammer proyeccion, detencion. Defensor: gyaku gedan'),
  ('TEC3030', 'Posicion: tai gamae. Atacante: ura ken tsuki komi o shuto uchi. Defensor: jun zuki'),
  ('TEC3031', 'Posicion: hiraki gamae. Atacante: intento de ippon se nage. Defensor: manji; una mano'),
  ('TEC3032', 'Posicion: hiraki gamae. Atacante: intento de se nage. Defensor: manji; jun mawashi'),
  ('TEC3033', 'Posicion: hiraki gamae. Atacante: intento de se nage. Defensor: manji; chudan jun zuki'),
  ('TEC3034', 'Posicion: hiraki gamae. Atacante: intento de se nage. Defensor: manji; golpea chokyu'),
  ('TEC3035', 'Posicion: hiraki gamae. Atacante: shikake waza; konoha gatame'),
  ('TEC3036', 'Posicion: hiraki gamae. Atacante: shikake waza'),
  ('TEC3037', 'Posicion: hiraki gamae. Atacante: intento de konoha atacar'),
  ('TEC3038', 'Posicion: hiraki gamae. Como en okuri gote. Atacante: suelta el agarre'),
  ('TEC3039', 'Posicion: hiraki gamae. Como en okuri gote. Atacante: gira hacia fuera under'),
  ('TEC3040', 'Posicion: tai gamae. Atacante: saludo de manos & aprieta. Defensor: ura gassho gatame 3dan rd'),
  ('TEC4036', 'Posicion: hiraki gamae. Defensor: jo chu ren han ko, despues uchi uke zuki'),
  ('TEC4037', 'Posicion: hiraki gamae. Atacante: ni ren uke vs geri, keri kaeshi 4dan th'),
  ('TEC4001', 'Posicion: tai gamae. Atacante: agarre tipo judo (aiyotsu, solapa alta y manga)'),
  ('TEC4002', 'Posicion: tai gamae. Atacante: empuja alejando a resistir bukkotsu'),
  ('TEC4003', 'Posicion: cualquier kamae indicado. Atacante: agarra el cuello desde atras & kari ashi'),
  ('TEC4004', 'Posicion: tai gamae. Atacante: estrangulacion. Defensor: shuho; atacar muneca inferior'),
  ('TEC4005', 'Posicion: tai gamae. Atacante: estrangulacion con top arm. Defensor: se nage'),
  ('TEC4006', 'Posicion: tai gamae. Atacante: atacar'),
  ('TEC4007', 'Posicion: tai gamae. Defensor: Desde hangetsu geri'),
  ('TEC4008', 'Posicion: hiraki gamae. entrelaza los dedos. Defensor: maki (‘lose’ kumade) o dori'),
  ('TEC4009', 'Posicion: tai gamae. ambas manos'),
  ('TEC4010', 'Posicion: hiraki gamae. mismo lado grip, dos formas'),
  ('TEC_005084', 'Posicion: hiraki gamae. mismo lado grip, dos formas'),
  ('TEC4011', 'Posicion: hiraki gamae. Atacante: shikake; kannuki gatame'),
  ('TEC4012', 'Posicion: hiraki gamae. Atacante: tembin cuando kannuki okuri falla'),
  ('TEC4013', 'Posicion: cualquier kamae indicado. Defensor: ''tate ichiji'' cuando gyaku gote falla'),
  ('TEC4014', 'Posicion: tai gamae. cruzado grip palmas o pulgares'),
  ('TEC_005085', 'Posicion: tai gamae. cruzado grip palmas o pulgares'),
  ('TEC4015', 'Posicion: cualquier kamae indicado. Atacante: cruzado agarra la manga (alta). Defensor: gyaku waza'),
  ('TEC4016', 'Posicion: cualquier kamae indicado. Atacante: cruzado agarra la manga (baja). Defensor: envuelve el brazo'),
  ('TEC4017', 'Posicion: tai gamae. Atacante: furi zuki. Defensor: nai wanto a tenchu, hook'),
  ('TEC4018', 'Posicion: tai gamae. Atacante: gyaku zuki. Defensor: midare; kannuki'),
  ('TEC4019', 'Posicion: hiraki gamae. Atacante: gyaku zuki. Defensor: midare, kannuki'),
  ('TEC4020', 'Posicion: hiraki gamae. Atacante: intento de ippon se nage. Defensor: manji; una mano'),
  ('TEC4021', 'Posicion: tai gamae. Defensor: cambia la direccion cuando omote falla'),
  ('TEC4022', 'Posicion: tai gamae. Atacante: agarre tipo judo, tira. Defensor: nai wanto a tenchu'),
  ('TEC4023', 'Posicion: tai gamae. Atacante: intento de katate nage'),
  ('TEC4024', 'Posicion: hiraki gamae. Atacante: Como en tsuki nuki (empuja hacia abajo)'),
  ('TEC4025', 'Posicion: tai gamae. Atacante: Como en sankaku nuki'),
  ('TEC4026', 'Posicion: hiraki gamae. Atacante: agarra la solapa alta cerca del cuello. Defensor: aiki gamae'),
  ('TEC4027', 'Posicion: cualquier kamae indicado. Atacante: agarra el cuello desde atras, kari ashi'),
  ('TEC4028', 'Posicion: cualquier kamae indicado. Atacante: abrazo desde atras Desde atras. Defensor: yahazu shuho, kinteki uchi'),
  ('TEC4029', 'Posicion: cualquier kamae indicado. Atacante: agarra el cuello desde atras. Defensor: girar, envuelve el brazo'),
  ('TEC4030', 'Posicion: cualquier kamae indicado. Atacante: agarra la manga Desde atras. Defensor: tembin'),
  ('TEC4031', 'Posicion: tai gamae. Atacante: furi zuki. Defensor: kakete uke'),
  ('TEC4032', 'Posicion: tai gamae. Atacante: furi zuki, retrocede tirando'),
  ('TEC4033', 'Posicion: tai gamae. Atacante: shikake waza; choji a yokei'),
  ('TEC4034', 'Posicion: tai gamae. Atacante: Desde gassho choji, o directo away'),
  ('TEC4035', 'Posicion: cualquier kamae indicado. Defensor: sokuto geri; empuja alejando o manos hacia abajo'),
  ('TEC_005086', 'Posicion: cualquier kamae indicado. Defensor: sokuto geri; empuja alejando o manos hacia abajo'),
  ('TEC5001', 'Posicion: tai gamae. Atacante: shikake waza; kannuki primero'),
  ('TEC5002', 'Posicion: tai gamae. Atacante: shikake waza; empuja hacia arriba under dai kento'),
  ('TEC5003', 'Posicion: tai gamae. Atacante: shikake waza'),
  ('TEC5004', 'Posicion: hiraki gamae. Defensor: midare gamae'),
  ('TEC5005', 'Posicion: tai gamae. Atacante: agarra la solapa & empuja con palma'),
  ('TEC5006', 'Posicion: tai gamae. Atacante: Como en tekubi dori, tira hacia abajo. Defensor: atacar chusho'),
  ('TEC5007', 'Posicion: cualquier kamae indicado. Atacante: agarra el pelo desde delante'),
  ('TEC5008', 'Posicion: hiraki gamae. ofrece la mano levantada. Atacante: agarra la manga'),
  ('TEC5009', 'Posicion: tai gamae. agarre tipo sumo. Defensor: hiza geri, koshi nage'),
  ('TEC5010', 'Posicion: tai gamae. agarre tipo sumo. Defensor: hiza geri, tembin'),
  ('TEC5011', 'Posicion: cualquier kamae indicado. Atacante: agarra el cinturon palma hacia abajo, o palma hacia arriba'),
  ('TEC5012', 'Posicion: hiraki gamae. Atacante: agarra la manga o muneca para kata guruma proyeccion'),
  ('TEC5013', 'Posicion: cualquier kamae indicado. Atacante: mawashi geri. Defensor: atrapa la pierna; atacar shokin'),
  ('TEC_005087', 'Posicion: cualquier kamae indicado. Atacante: mawashi geri. Defensor: atrapa la pierna; atacar shokin'),
  ('TEC5014', 'Posicion: hiraki gamae. Defensor: seiza; atacar san inko, kekkai, yako'),
  ('TEC_005088', 'Posicion: hiraki gamae. Defensor: seiza; atacar san inko, kekkai, yako'),
  ('TEC5015', 'Posicion: cualquier kamae indicado. Atacante: shikake, sutemi waza; mawashi geri primero'),
  ('TEC_005089', 'Posicion: cualquier kamae indicado. Atacante: shikake, sutemi waza; mawashi geri primero'),
  ('TEC5016', 'Posicion: ataque desde atras. Atacante: empuja head hacia abajo Desde atras'),
  ('TEC5017', 'Posicion: tai gamae. Atacante: agarra la manga. Defensor: gyaku gedan; envuelve el brazo'),
  ('TEC5018', 'Posicion: hiraki gamae. Atacante: agarre cruzado de manga baja. Defensor: gyaku gedan'),
  ('TEC5019', 'Posicion: hiraki gamae. Atacante: agarra la solapa high, by neck'),
  ('TEC5020', 'Posicion: tai gamae. Atacante: estrangulacion a'),
  ('TEC5021', 'Posicion: tai gamae. Como en ryote kannuki nage'),
  ('TEC5022', 'Posicion: hiraki gamae. Atacante: shikake waza; pasa por debajo del brazo'),
  ('TEC5023', 'Posicion: tai gamae. Atacante: shikake waza; cruzado agarra, ura taoshi'),
  ('TEC5024', 'Posicion: tai gamae. Atacante: shikake waza; Desde saludo de manos'),
  ('TEC5025', 'Posicion: hiraki gamae. Defensor: ''win'' kumade gaeshi; atacar kokoku, ura taoshi'),
  ('TEC5026', 'Posicion: hiraki gamae. Defensor: shuto / wanto a elbow'),
  ('TEC5027', 'Posicion: cualquier kamae indicado. Shikake o Desde kote nage, ura'),
  ('TEC5028', 'Posicion: cualquier kamae indicado. Shikake o Desde kote nage, omote'),
  ('TEC5029', 'Posicion: cualquier kamae indicado. Como en tai ten ichi o tsuki ten ichi')
)
update public.techniques t
set summary_es = summaries.summary_es,
    updated_at = now()
from summaries
where t.legacy_id = summaries.legacy_id;

update public.technical_plans tp
set summary_es = t.summary_es,
    updated_at = now()
from public.techniques t
where tp.technique_id = t.id
  and t.summary_es is not null;
